using Saltoapis.Nebula.IntercomAdaptor.V1.Request;
using Saltoapis.Nebula.IntercomAdaptor.V1.Response;

namespace Saltoapis.Nebula.IntercomAdaptor.V1
{
    /// <summary>Holder for reflection information generated from salto/nebula/intercomadaptor/v1/intercom_adaptor.proto</summary>
    public static partial class IntercomAdaptorReflection
    {

        /// <summary>File descriptor for salto/nebula/intercomadaptor/v1/intercom_adaptor.proto</summary>
        public static FileDescriptor Descriptor
        {
            get { return descriptor; }
        }

        private static FileDescriptor descriptor;

        static IntercomAdaptorReflection()
        {
            byte[] descriptorData = System.Convert.FromBase64String(
                string.Concat(
                  "CjZzYWx0by9uZWJ1bGEvaW50ZXJjb21hZGFwdG9yL3YxL2ludGVyY29tX2Fk",
                  "YXB0b3IucHJvdG8SH3NhbHRvLm5lYnVsYS5pbnRlcmNvbWFkYXB0b3IudjEa",
                  "G2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bxogZ29vZ2xlL3Byb3RvYnVm",
                  "L2ZpZWxkX21hc2sucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAu",
                  "cHJvdG8aJHNhbHRvL2xvbmdydW5uaW5nL3YxL29wZXJhdGlvbi5wcm90bxon",
                  "c2FsdG8vbmVidWxhL3R5cGUvZGV2aWNlX21ldGFkYXRhLnByb3RvIoEECg9J",
                  "bnRlcmNvbUFkYXB0b3ISDAoEbmFtZRgBIAEoCRIUCgxkaXNwbGF5X25hbWUY",
                  "AiABKAkSFgoJZGV2aWNlX2lkGAMgASgJSAGIAQESEQoHZ2F0ZXdheRgEIAEo",
                  "CUgAEhIKCGV4dGVuZGVyGAUgASgJSAASUgoNYWNjZXNzX3BvaW50cxgGIAMo",
                  "CzI7LnNhbHRvLm5lYnVsYS5pbnRlcmNvbWFkYXB0b3IudjEuSW50ZXJjb21B",
                  "ZGFwdG9yQWNjZXNzUG9pbnQSEwoLaW5pdGlhbGl6ZWQYByABKAgSOgoPZGV2",
                  "aWNlX21ldGFkYXRhGBAgASgLMiEuc2FsdG8ubmVidWxhLnR5cGUuRGV2aWNl",
                  "TWV0YWRhdGESEAoIb3V0ZGF0ZWQYCCABKAgSEQoJY29ubmVjdGVkGAkgASgI",
                  "EhMKC2xvd19iYXR0ZXJ5GAogASgIEjMKD2xhc3RfZXZlbnRfdGltZRgLIAEo",
                  "CzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFQoIaW50ZXJjb20YDCAB",
                  "KAlIAogBARIOCgZwaG90b3MYDSADKAkSEgoKcGhvdG9fdXJpcxgOIAMoCRIQ",
                  "CghyZWFkaW5ncxgPIAMoCUIPCg1wYXJlbnRfZGV2aWNlQgwKCl9kZXZpY2Vf",
                  "aWRCCwoJX2ludGVyY29tImIKGkludGVyY29tQWRhcHRvckFjY2Vzc1BvaW50",
                  "EhQKDGFjY2Vzc19wb2ludBgBIAEoCRIbCg5mcmFtZV9zZXR0aW5ncxgCIAEo",
                  "DEgAiAEBQhEKD19mcmFtZV9zZXR0aW5ncyK0AQocQ3JlYXRlSW50ZXJjb21B",
                  "ZGFwdG9yUmVxdWVzdBIOCgZwYXJlbnQYASABKAkSIAoTaW50ZXJjb21fYWRh",
                  "cHRvcl9pZBgCIAEoCUgAiAEBEkoKEGludGVyY29tX2FkYXB0b3IYAyABKAsy",
                  "MC5zYWx0by5uZWJ1bGEuaW50ZXJjb21hZGFwdG9yLnYxLkludGVyY29tQWRh",
                  "cHRvckIWChRfaW50ZXJjb21fYWRhcHRvcl9pZCIpChlHZXRJbnRlcmNvbUFk",
                  "YXB0b3JSZXF1ZXN0EgwKBG5hbWUYASABKAkidgobTGlzdEludGVyY29tQWRh",
                  "cHRvcnNSZXF1ZXN0Eg4KBnBhcmVudBgBIAEoCRIRCglwYWdlX3NpemUYAiAB",
                  "KAUSEgoKcGFnZV90b2tlbhgDIAEoCRIOCgZmaWx0ZXIYBCABKAkSEAoIb3Jk",
                  "ZXJfYnkYBSABKAkihAEKHExpc3RJbnRlcmNvbUFkYXB0b3JzUmVzcG9uc2US",
                  "SwoRaW50ZXJjb21fYWRhcHRvcnMYASADKAsyMC5zYWx0by5uZWJ1bGEuaW50",
                  "ZXJjb21hZGFwdG9yLnYxLkludGVyY29tQWRhcHRvchIXCg9uZXh0X3BhZ2Vf",
                  "dG9rZW4YAiABKAkimwEKHFVwZGF0ZUludGVyY29tQWRhcHRvclJlcXVlc3QS",
                  "SgoQaW50ZXJjb21fYWRhcHRvchgBIAEoCzIwLnNhbHRvLm5lYnVsYS5pbnRl",
                  "cmNvbWFkYXB0b3IudjEuSW50ZXJjb21BZGFwdG9yEi8KC3VwZGF0ZV9tYXNr",
                  "GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkZpZWxkTWFzayIsChxEZWxldGVJ",
                  "bnRlcmNvbUFkYXB0b3JSZXF1ZXN0EgwKBG5hbWUYASABKAkiPQoaQmluZElu",
                  "dGVyY29tQWRhcHRvclJlcXVlc3QSDAoEbmFtZRgBIAEoCRIRCglkZXZpY2Vf",
                  "aWQYAiABKAkiHQobQmluZEludGVyY29tQWRhcHRvclJlc3BvbnNlIjsKHFVu",
                  "YmluZEludGVyY29tQWRhcHRvclJlcXVlc3QSDAoEbmFtZRgBIAEoCRINCgVm",
                  "b3JjZRgCIAEoCCIfCh1VbmJpbmRJbnRlcmNvbUFkYXB0b3JSZXNwb25zZSIw",
                  "CiBJbml0aWFsaXplSW50ZXJjb21BZGFwdG9yUmVxdWVzdBIMCgRuYW1lGAEg",
                  "ASgJIiMKIUluaXRpYWxpemVJbnRlcmNvbUFkYXB0b3JSZXNwb25zZSI9CiFJ",
                  "bml0aWFsaXplSW50ZXJjb21BZGFwdG9yTWV0YWRhdGESGAoQcHJvZ3Jlc3Nf",
                  "cGVyY2VudBgBIAEoBSIvCh9Db25maWd1cmVJbnRlcmNvbUFkYXB0b3JSZXF1",
                  "ZXN0EgwKBG5hbWUYASABKAkiIgogQ29uZmlndXJlSW50ZXJjb21BZGFwdG9y",
                  "UmVzcG9uc2UiIgogQ29uZmlndXJlSW50ZXJjb21BZGFwdG9yTWV0YWRhdGEi",
                  "KwobUmVzZXRJbnRlcmNvbUFkYXB0b3JSZXF1ZXN0EgwKBG5hbWUYASABKAki",
                  "HgocUmVzZXRJbnRlcmNvbUFkYXB0b3JSZXNwb25zZSIeChxSZXNldEludGVy",
                  "Y29tQWRhcHRvck1ldGFkYXRhIkAKJFVwZGF0ZUludGVyY29tQWRhcHRvckZp",
                  "cm13YXJlUmVxdWVzdBIYChBpbnRlcmNvbV9hZGFwdG9yGAEgASgJIicKJVVw",
                  "ZGF0ZUludGVyY29tQWRhcHRvckZpcm13YXJlUmVzcG9uc2UiQQolVXBkYXRl",
                  "SW50ZXJjb21BZGFwdG9yRmlybXdhcmVNZXRhZGF0YRIYChBwcm9ncmVzc19w",
                  "ZXJjZW50GAEgASgFIj0KIUdlbmVyYXRlQXV0aG9yaXphdGlvblRva2VuUmVx",
                  "dWVzdBIYChBpbnRlcmNvbV9hZGFwdG9yGAEgASgJIkEKIkdlbmVyYXRlQXV0",
                  "aG9yaXphdGlvblRva2VuUmVzcG9uc2USGwoTYXV0aG9yaXphdGlvbl90b2tl",
                  "bhgBIAEoDCI+CiJHZW5lcmF0ZUZpcm13YXJlRG93bmxvYWRVcmlSZXF1ZXN0",
                  "EhgKEGludGVyY29tX2FkYXB0b3IYASABKAkiSwojR2VuZXJhdGVGaXJtd2Fy",
                  "ZURvd25sb2FkVXJpUmVzcG9uc2USFAoMZG93bmxvYWRfdXJpGAEgASgJEg4K",
                  "BmRpZ2VzdBgCIAEoCSIlCiNHZW5lcmF0ZUZpcm13YXJlRG93bmxvYWRVcmlN",
                  "ZXRhZGF0YTKUDgoWSW50ZXJjb21BZGFwdG9yU2VydmljZRKIAQoVQ3JlYXRl",
                  "SW50ZXJjb21BZGFwdG9yEj0uc2FsdG8ubmVidWxhLmludGVyY29tYWRhcHRv",
                  "ci52MS5DcmVhdGVJbnRlcmNvbUFkYXB0b3JSZXF1ZXN0GjAuc2FsdG8ubmVi",
                  "dWxhLmludGVyY29tYWRhcHRvci52MS5JbnRlcmNvbUFkYXB0b3ISggEKEkdl",
                  "dEludGVyY29tQWRhcHRvchI6LnNhbHRvLm5lYnVsYS5pbnRlcmNvbWFkYXB0",
                  "b3IudjEuR2V0SW50ZXJjb21BZGFwdG9yUmVxdWVzdBowLnNhbHRvLm5lYnVs",
                  "YS5pbnRlcmNvbWFkYXB0b3IudjEuSW50ZXJjb21BZGFwdG9yEpMBChRMaXN0",
                  "SW50ZXJjb21BZGFwdG9ycxI8LnNhbHRvLm5lYnVsYS5pbnRlcmNvbWFkYXB0",
                  "b3IudjEuTGlzdEludGVyY29tQWRhcHRvcnNSZXF1ZXN0Gj0uc2FsdG8ubmVi",
                  "dWxhLmludGVyY29tYWRhcHRvci52MS5MaXN0SW50ZXJjb21BZGFwdG9yc1Jl",
                  "c3BvbnNlEogBChVVcGRhdGVJbnRlcmNvbUFkYXB0b3ISPS5zYWx0by5uZWJ1",
                  "bGEuaW50ZXJjb21hZGFwdG9yLnYxLlVwZGF0ZUludGVyY29tQWRhcHRvclJl",
                  "cXVlc3QaMC5zYWx0by5uZWJ1bGEuaW50ZXJjb21hZGFwdG9yLnYxLkludGVy",
                  "Y29tQWRhcHRvchJuChVEZWxldGVJbnRlcmNvbUFkYXB0b3ISPS5zYWx0by5u",
                  "ZWJ1bGEuaW50ZXJjb21hZGFwdG9yLnYxLkRlbGV0ZUludGVyY29tQWRhcHRv",
                  "clJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSkAEKE0JpbmRJbnRl",
                  "cmNvbUFkYXB0b3ISOy5zYWx0by5uZWJ1bGEuaW50ZXJjb21hZGFwdG9yLnYx",
                  "LkJpbmRJbnRlcmNvbUFkYXB0b3JSZXF1ZXN0Gjwuc2FsdG8ubmVidWxhLmlu",
                  "dGVyY29tYWRhcHRvci52MS5CaW5kSW50ZXJjb21BZGFwdG9yUmVzcG9uc2US",
                  "lgEKFVVuYmluZEludGVyY29tQWRhcHRvchI9LnNhbHRvLm5lYnVsYS5pbnRl",
                  "cmNvbWFkYXB0b3IudjEuVW5iaW5kSW50ZXJjb21BZGFwdG9yUmVxdWVzdBo+",
                  "LnNhbHRvLm5lYnVsYS5pbnRlcmNvbWFkYXB0b3IudjEuVW5iaW5kSW50ZXJj",
                  "b21BZGFwdG9yUmVzcG9uc2USfwoZSW5pdGlhbGl6ZUludGVyY29tQWRhcHRv",
                  "chJBLnNhbHRvLm5lYnVsYS5pbnRlcmNvbWFkYXB0b3IudjEuSW5pdGlhbGl6",
                  "ZUludGVyY29tQWRhcHRvclJlcXVlc3QaHy5zYWx0by5sb25ncnVubmluZy52",
                  "MS5PcGVyYXRpb24SfQoYQ29uZmlndXJlSW50ZXJjb21BZGFwdG9yEkAuc2Fs",
                  "dG8ubmVidWxhLmludGVyY29tYWRhcHRvci52MS5Db25maWd1cmVJbnRlcmNv",
                  "bUFkYXB0b3JSZXF1ZXN0Gh8uc2FsdG8ubG9uZ3J1bm5pbmcudjEuT3BlcmF0",
                  "aW9uEnUKFFJlc2V0SW50ZXJjb21BZGFwdG9yEjwuc2FsdG8ubmVidWxhLmlu",
                  "dGVyY29tYWRhcHRvci52MS5SZXNldEludGVyY29tQWRhcHRvclJlcXVlc3Qa",
                  "Hy5zYWx0by5sb25ncnVubmluZy52MS5PcGVyYXRpb24ShwEKHVVwZGF0ZUlu",
                  "dGVyY29tQWRhcHRvckZpcm13YXJlEkUuc2FsdG8ubmVidWxhLmludGVyY29t",
                  "YWRhcHRvci52MS5VcGRhdGVJbnRlcmNvbUFkYXB0b3JGaXJtd2FyZVJlcXVl",
                  "c3QaHy5zYWx0by5sb25ncnVubmluZy52MS5PcGVyYXRpb24SpQEKGkdlbmVy",
                  "YXRlQXV0aG9yaXphdGlvblRva2VuEkIuc2FsdG8ubmVidWxhLmludGVyY29t",
                  "YWRhcHRvci52MS5HZW5lcmF0ZUF1dGhvcml6YXRpb25Ub2tlblJlcXVlc3Qa",
                  "Qy5zYWx0by5uZWJ1bGEuaW50ZXJjb21hZGFwdG9yLnYxLkdlbmVyYXRlQXV0",
                  "aG9yaXphdGlvblRva2VuUmVzcG9uc2USgwEKG0dlbmVyYXRlRmlybXdhcmVE",
                  "b3dubG9hZFVyaRJDLnNhbHRvLm5lYnVsYS5pbnRlcmNvbWFkYXB0b3IudjEu",
                  "R2VuZXJhdGVGaXJtd2FyZURvd25sb2FkVXJpUmVxdWVzdBofLnNhbHRvLmxv",
                  "bmdydW5uaW5nLnYxLk9wZXJhdGlvbkKVAgonY29tLnNhbHRvYXBpcy5uZWJ1",
                  "bGEuaW50ZXJjb21hZGFwdG9yLnYxQhRJbnRlcmNvbUFkYXB0b3JQcm90b1AB",
                  "WlRnaXRodWIuY29tL3NhbHRvYXBpcy1pbnRlcm5hbC9zYWx0b2FwaXMtZ28v",
                  "bmVidWxhL2ludGVyY29tYWRhcHRvci92MTtpbnRlcmNvbWFkYXB0b3KqAiNT",
                  "YWx0b2FwaXMuTmVidWxhLkludGVyY29tQWRhcHRvci5WMcoCI1NhbHRvYXBp",
                  "c1xOZWJ1bGFcSW50ZXJjb21BZGFwdG9yXFYx4gIvR1BCTWV0YWRhdGFcU2Fs",
                  "dG9hcGlzXE5lYnVsYVxJbnRlcmNvbUFkYXB0b3JcVjFiBnByb3RvMw=="));
            descriptor = FileDescriptor.FromGeneratedCode(descriptorData,
                [Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, Google.Protobuf.WellKnownTypes.FieldMaskReflection.Descriptor, Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, Longrunning.V1.OperationReflection.Descriptor, Type.DeviceMetadataReflection.Descriptor,],
                new GeneratedClrTypeInfo(null, null, [
            new(typeof(IntercomAdaptor), IntercomAdaptor.Parser, ["Name", "DisplayName", "DeviceId", "Gateway", "Extender", "AccessPoints", "Initialized", "DeviceMetadata", "Outdated", "Connected", "LowBattery", "LastEventTime", "Intercom", "Photos", "PhotoUris", "Readings"], ["ParentDevice", "DeviceId", "Intercom"], null, null, null),
            new(typeof(IntercomAdaptorAccessPoint), IntercomAdaptorAccessPoint.Parser, ["AccessPoint", "FrameSettings"], ["FrameSettings"], null, null, null),
            new(typeof(CreateIntercomAdaptorRequest), CreateIntercomAdaptorRequest.Parser, ["Parent", "IntercomAdaptorId", "IntercomAdaptor"], ["IntercomAdaptorId"], null, null, null),
            new(typeof(GetIntercomAdaptorRequest), GetIntercomAdaptorRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ListIntercomAdaptorsRequest), ListIntercomAdaptorsRequest.Parser, ["Parent", "PageSize", "PageToken", "Filter", "OrderBy"], null, null, null, null),
            new(typeof(ListIntercomAdaptorsResponse), ListIntercomAdaptorsResponse.Parser, ["IntercomAdaptors", "NextPageToken"], null, null, null, null),
            new(typeof(UpdateIntercomAdaptorRequest), UpdateIntercomAdaptorRequest.Parser, ["IntercomAdaptor", "UpdateMask"], null, null, null, null),
            new(typeof(DeleteIntercomAdaptorRequest), DeleteIntercomAdaptorRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(BindIntercomAdaptorRequest), BindIntercomAdaptorRequest.Parser, ["Name", "DeviceId"], null, null, null, null),
            new(typeof(BindIntercomAdaptorResponse), BindIntercomAdaptorResponse.Parser, null, null, null, null, null),
            new(typeof(UnbindIntercomAdaptorRequest), UnbindIntercomAdaptorRequest.Parser, ["Name", "Force"], null, null, null, null),
            new(typeof(UnbindIntercomAdaptorResponse), UnbindIntercomAdaptorResponse.Parser, null, null, null, null, null),
            new(typeof(InitializeIntercomAdaptorRequest), InitializeIntercomAdaptorRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(InitializeIntercomAdaptorResponse), InitializeIntercomAdaptorResponse.Parser, null, null, null, null, null),
            new(typeof(InitializeIntercomAdaptorMetadata), InitializeIntercomAdaptorMetadata.Parser, ["ProgressPercent"], null, null, null, null),
            new(typeof(ConfigureIntercomAdaptorRequest), ConfigureIntercomAdaptorRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ConfigureIntercomAdaptorResponse), ConfigureIntercomAdaptorResponse.Parser, null, null, null, null, null),
            new(typeof(ConfigureIntercomAdaptorMetadata), ConfigureIntercomAdaptorMetadata.Parser, null, null, null, null, null),
            new(typeof(ResetIntercomAdaptorRequest), ResetIntercomAdaptorRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ResetIntercomAdaptorResponse), ResetIntercomAdaptorResponse.Parser, null, null, null, null, null),
            new(typeof(ResetIntercomAdaptorMetadata), ResetIntercomAdaptorMetadata.Parser, null, null, null, null, null),
            new(typeof(UpdateIntercomAdaptorFirmwareRequest), UpdateIntercomAdaptorFirmwareRequest.Parser, ["IntercomAdaptor"], null, null, null, null),
            new(typeof(UpdateIntercomAdaptorFirmwareResponse), UpdateIntercomAdaptorFirmwareResponse.Parser, null, null, null, null, null),
            new(typeof(UpdateIntercomAdaptorFirmwareMetadata), UpdateIntercomAdaptorFirmwareMetadata.Parser, ["ProgressPercent"], null, null, null, null),
            new(typeof(GenerateAuthorizationTokenRequest), GenerateAuthorizationTokenRequest.Parser, ["IntercomAdaptor"], null, null, null, null),
            new(typeof(GenerateAuthorizationTokenResponse), GenerateAuthorizationTokenResponse.Parser, ["AuthorizationToken"], null, null, null, null),
            new(typeof(GenerateFirmwareDownloadUriRequest), GenerateFirmwareDownloadUriRequest.Parser, ["IntercomAdaptor"], null, null, null, null),
            new(typeof(GenerateFirmwareDownloadUriResponse), GenerateFirmwareDownloadUriResponse.Parser, ["DownloadUri", "Digest"], null, null, null, null),
            new(typeof(GenerateFirmwareDownloadUriMetadata), GenerateFirmwareDownloadUriMetadata.Parser, null, null, null, null, null)
                ]));
        }

    }


}
