using Saltoapis.Nebula.User.V1.Request;
using Saltoapis.Nebula.User.V1.Response;

namespace Saltoapis.Nebula.User.V1
{
    /// <summary>Holder for reflection information generated from salto/nebula/user/v1/user.proto</summary>
    public static partial class UserReflection
    {

        /// <summary>File descriptor for salto/nebula/user/v1/user.proto</summary>
        public static FileDescriptor Descriptor
        {
            get { return descriptor; }
        }

        private static FileDescriptor descriptor;

        static UserReflection()
        {
            byte[] descriptorData = System.Convert.FromBase64String(
                string.Concat(
                  "Ch9zYWx0by9uZWJ1bGEvdXNlci92MS91c2VyLnByb3RvEhRzYWx0by5uZWJ1",
                  "bGEudXNlci52MRobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvGiBnb29n",
                  "bGUvcHJvdG9idWYvZmllbGRfbWFzay5wcm90bxofZ29vZ2xlL3Byb3RvYnVm",
                  "L3RpbWVzdGFtcC5wcm90bxokc2FsdG8vbG9uZ3J1bm5pbmcvdjEvb3BlcmF0",
                  "aW9uLnByb3RvGiBzYWx0by9uZWJ1bGEvdHlwZS9zY2hlZHVsZS5wcm90byLy",
                  "BAoEVXNlchIMCgRuYW1lGAEgASgJEhMKBnBhcmVudBgCIAEoCUgAiAEBEhIK",
                  "CmdpdmVuX25hbWUYAyABKAkSGAoLZmFtaWx5X25hbWUYBCABKAlIAYgBARIU",
                  "CgxkaXNwbGF5X25hbWUYBSABKAkSEgoFZW1haWwYBiABKAlIAogBARIxCg1h",
                  "Y3RpdmF0ZV90aW1lGAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFt",
                  "cBIvCgtleHBpcmVfdGltZRgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1l",
                  "c3RhbXASEgoFcGhvdG8YCSABKAlIA4gBARIRCglwaG90b191cmkYCiABKAkS",
                  "LwoIY2FyZF9rZXkYCyABKAsyHS5zYWx0by5uZWJ1bGEudXNlci52MS5DYXJk",
                  "S2V5EjsKDmVsZWN0cm9uaWNfa2V5GBAgASgLMiMuc2FsdG8ubmVidWxhLnVz",
                  "ZXIudjEuRWxlY3Ryb25pY0tleRItCgdhcHBfa2V5GAwgASgLMhwuc2FsdG8u",
                  "bmVidWxhLnVzZXIudjEuQXBwS2V5EjMKCndhbGxldF9rZXkYDSABKAsyHy5z",
                  "YWx0by5uZWJ1bGEudXNlci52MS5XYWxsZXRLZXkSMAoIcGFzc2NvZGUYDyAB",
                  "KAsyHi5zYWx0by5uZWJ1bGEudXNlci52MS5QYXNzY29kZRIPCgdibG9ja2Vk",
                  "GA4gASgIEhQKB21hbmFnZXIYESABKAlIBIgBAUIJCgdfcGFyZW50Qg4KDF9m",
                  "YW1pbHlfbmFtZUIICgZfZW1haWxCCAoGX3Bob3RvQgoKCF9tYW5hZ2VyIucC",
                  "Cg9Vc2VyQWNjZXNzUmlnaHQSDAoEbmFtZRgBIAEoCRIUCgxhY2Nlc3Nfcmln",
                  "aHQYAiABKAkSFAoMZGlzcGxheV9uYW1lGAMgASgJEi4KCXNjaGVkdWxlcxgE",
                  "IAMoCzIbLnNhbHRvLm5lYnVsYS50eXBlLlNjaGVkdWxlEjgKE2VmZmVjdGl2",
                  "ZV9zY2hlZHVsZXMYBSADKAsyGy5zYWx0by5uZWJ1bGEudHlwZS5TY2hlZHVs",
                  "ZRI2Cg1hY3RpdmF0ZV90aW1lGAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRp",
                  "bWVzdGFtcEgAiAEBEjQKC2V4cGlyZV90aW1lGAcgASgLMhouZ29vZ2xlLnBy",
                  "b3RvYnVmLlRpbWVzdGFtcEgBiAEBEhQKB21hbmFnZXIYCCABKAlIAogBAUIQ",
                  "Cg5fYWN0aXZhdGVfdGltZUIOCgxfZXhwaXJlX3RpbWVCCgoIX21hbmFnZXIi",
                  "tQEKB0NhcmRLZXkSDAoEbmFtZRgBIAEoCRILCgN1aWQYAiABKAkSMgoFc3Rh",
                  "dGUYAyABKA4yIy5zYWx0by5uZWJ1bGEudXNlci52MS5DYXJkS2V5LlN0YXRl",
                  "EhAKCG91dGRhdGVkGAQgASgIIkkKBVN0YXRlEhUKEVNUQVRFX1VOU1BFQ0lG",
                  "SUVEEAASEAoMTk9UX0FTU0lHTkVEEAESCwoHUEVORElORxACEgoKBkFDVElW",
                  "RRADIqYBCgZBcHBLZXkSDAoEbmFtZRgBIAEoCRIxCgVzdGF0ZRgCIAEoDjIi",
                  "LnNhbHRvLm5lYnVsYS51c2VyLnYxLkFwcEtleS5TdGF0ZRIQCghvdXRkYXRl",
                  "ZBgDIAEoCCJJCgVTdGF0ZRIVChFTVEFURV9VTlNQRUNJRklFRBAAEhAKDE5P",
                  "VF9BU1NJR05FRBABEgsKB1BFTkRJTkcQAhIKCgZBQ1RJVkUQAyKsAQoJV2Fs",
                  "bGV0S2V5EgwKBG5hbWUYASABKAkSNAoFc3RhdGUYAiABKA4yJS5zYWx0by5u",
                  "ZWJ1bGEudXNlci52MS5XYWxsZXRLZXkuU3RhdGUSEAoIb3V0ZGF0ZWQYAyAB",
                  "KAgiSQoFU3RhdGUSFQoRU1RBVEVfVU5TUEVDSUZJRUQQABIQCgxOT1RfQVNT",
                  "SUdORUQQARILCgdQRU5ESU5HEAISCgoGQUNUSVZFEAMiiwEKCFBhc3Njb2Rl",
                  "EgwKBG5hbWUYASABKAkSMwoFc3RhdGUYAiABKA4yJC5zYWx0by5uZWJ1bGEu",
                  "dXNlci52MS5QYXNzY29kZS5TdGF0ZSI8CgVTdGF0ZRIVChFTVEFURV9VTlNQ",
                  "RUNJRklFRBAAEhAKDE5PVF9BU1NJR05FRBABEgoKBkFDVElWRRACIscBCg1F",
                  "bGVjdHJvbmljS2V5EgwKBG5hbWUYASABKAkSEQoJZGV2aWNlX2lkGAIgASgJ",
                  "EjgKBXN0YXRlGAMgASgOMikuc2FsdG8ubmVidWxhLnVzZXIudjEuRWxlY3Ry",
                  "b25pY0tleS5TdGF0ZRIQCghvdXRkYXRlZBgEIAEoCCJJCgVTdGF0ZRIVChFT",
                  "VEFURV9VTlNQRUNJRklFRBAAEhAKDE5PVF9BU1NJR05FRBABEgsKB1BFTkRJ",
                  "TkcQAhIKCgZBQ1RJVkUQAyJvChFDcmVhdGVVc2VyUmVxdWVzdBIOCgZwYXJl",
                  "bnQYASABKAkSFAoHdXNlcl9pZBgCIAEoCUgAiAEBEigKBHVzZXIYAyABKAsy",
                  "Gi5zYWx0by5uZWJ1bGEudXNlci52MS5Vc2VyQgoKCF91c2VyX2lkIh4KDkdl",
                  "dFVzZXJSZXF1ZXN0EgwKBG5hbWUYASABKAkiNQoUQmF0Y2hHZXRVc2Vyc1Jl",
                  "cXVlc3QSDgoGcGFyZW50GAEgASgJEg0KBW5hbWVzGAIgAygJIkIKFUJhdGNo",
                  "R2V0VXNlcnNSZXNwb25zZRIpCgV1c2VycxgBIAMoCzIaLnNhbHRvLm5lYnVs",
                  "YS51c2VyLnYxLlVzZXIiawoQTGlzdFVzZXJzUmVxdWVzdBIOCgZwYXJlbnQY",
                  "ASABKAkSEQoJcGFnZV9zaXplGAIgASgFEhIKCnBhZ2VfdG9rZW4YAyABKAkS",
                  "DgoGZmlsdGVyGAQgASgJEhAKCG9yZGVyX2J5GAUgASgJImsKEUxpc3RVc2Vy",
                  "c1Jlc3BvbnNlEikKBXVzZXJzGAEgAygLMhouc2FsdG8ubmVidWxhLnVzZXIu",
                  "djEuVXNlchIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkSEgoKdG90YWxfc2l6",
                  "ZRgDIAEoBSJuChFVcGRhdGVVc2VyUmVxdWVzdBIoCgR1c2VyGAEgASgLMhou",
                  "c2FsdG8ubmVidWxhLnVzZXIudjEuVXNlchIvCgt1cGRhdGVfbWFzaxgCIAEo",
                  "CzIaLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE1hc2siIQoRRGVsZXRlVXNlclJl",
                  "cXVlc3QSDAoEbmFtZRgBIAEoCSIgChBCbG9ja1VzZXJSZXF1ZXN0EgwKBG5h",
                  "bWUYASABKAkiEwoRQmxvY2tVc2VyUmVzcG9uc2UiIgoSVW5ibG9ja1VzZXJS",
                  "ZXF1ZXN0EgwKBG5hbWUYASABKAkiFQoTVW5ibG9ja1VzZXJSZXNwb25zZSJw",
                  "ChxDcmVhdGVVc2VyQWNjZXNzUmlnaHRSZXF1ZXN0Eg4KBnBhcmVudBgBIAEo",
                  "CRJAChF1c2VyX2FjY2Vzc19yaWdodBgCIAEoCzIlLnNhbHRvLm5lYnVsYS51",
                  "c2VyLnYxLlVzZXJBY2Nlc3NSaWdodCIpChlHZXRVc2VyQWNjZXNzUmlnaHRS",
                  "ZXF1ZXN0EgwKBG5hbWUYASABKAkidgobTGlzdFVzZXJBY2Nlc3NSaWdodHNS",
                  "ZXF1ZXN0Eg4KBnBhcmVudBgBIAEoCRIRCglwYWdlX3NpemUYAiABKAUSEgoK",
                  "cGFnZV90b2tlbhgDIAEoCRIOCgZmaWx0ZXIYBCABKAkSEAoIb3JkZXJfYnkY",
                  "BSABKAkiegocTGlzdFVzZXJBY2Nlc3NSaWdodHNSZXNwb25zZRJBChJ1c2Vy",
                  "X2FjY2Vzc19yaWdodHMYASADKAsyJS5zYWx0by5uZWJ1bGEudXNlci52MS5V",
                  "c2VyQWNjZXNzUmlnaHQSFwoPbmV4dF9wYWdlX3Rva2VuGAIgASgJIpEBChxV",
                  "cGRhdGVVc2VyQWNjZXNzUmlnaHRSZXF1ZXN0EkAKEXVzZXJfYWNjZXNzX3Jp",
                  "Z2h0GAEgASgLMiUuc2FsdG8ubmVidWxhLnVzZXIudjEuVXNlckFjY2Vzc1Jp",
                  "Z2h0Ei8KC3VwZGF0ZV9tYXNrGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkZp",
                  "ZWxkTWFzayIsChxEZWxldGVVc2VyQWNjZXNzUmlnaHRSZXF1ZXN0EgwKBG5h",
                  "bWUYASABKAkiMQoUQXNzaWduQ2FyZEtleVJlcXVlc3QSDAoEbmFtZRgBIAEo",
                  "CRILCgN1aWQYAiABKAkiJAoUQ2FuY2VsQ2FyZEtleVJlcXVlc3QSDAoEbmFt",
                  "ZRgBIAEoCSJyChRFbmNvZGVDYXJkS2V5UmVxdWVzdBIMCgRuYW1lGAEgASgJ",
                  "EhEKB2VuY29kZXIYAiABKAlIABIZCg9lbGVjdHJvbmljX2xvY2sYAyABKAlI",
                  "ABIUCgpjb250cm9sbGVyGAQgASgJSABCCAoGZGV2aWNlIhcKFUVuY29kZUNh",
                  "cmRLZXlSZXNwb25zZSIXChVFbmNvZGVDYXJkS2V5TWV0YWRhdGEiIwoTQXNz",
                  "aWduQXBwS2V5UmVxdWVzdBIMCgRuYW1lGAEgASgJIiMKE0NhbmNlbEFwcEtl",
                  "eVJlcXVlc3QSDAoEbmFtZRgBIAEoCSIoChhDb21wdXRlQXBwS2V5RGF0YVJl",
                  "cXVlc3QSDAoEbmFtZRgBIAEoCSIpChlDb21wdXRlQXBwS2V5RGF0YVJlc3Bv",
                  "bnNlEgwKBGRhdGEYASABKAwiJgoWQXNzaWduV2FsbGV0S2V5UmVxdWVzdBIM",
                  "CgRuYW1lGAEgASgJImIKF0Fzc2lnbldhbGxldEtleVJlc3BvbnNlEjMKCndh",
                  "bGxldF9rZXkYASABKAsyHy5zYWx0by5uZWJ1bGEudXNlci52MS5XYWxsZXRL",
                  "ZXkSEgoKYWNjZXNzX3VyaRgCIAEoCSImChZDYW5jZWxXYWxsZXRLZXlSZXF1",
                  "ZXN0EgwKBG5hbWUYASABKAkiTgoXQ2FuY2VsV2FsbGV0S2V5UmVzcG9uc2US",
                  "MwoKd2FsbGV0X2tleRgBIAEoCzIfLnNhbHRvLm5lYnVsYS51c2VyLnYxLldh",
                  "bGxldEtleSIlChVBc3NpZ25QYXNzY29kZVJlcXVlc3QSDAoEbmFtZRgBIAEo",
                  "CSJZChZBc3NpZ25QYXNzY29kZVJlc3BvbnNlEjAKCHBhc3Njb2RlGAEgASgL",
                  "Mh4uc2FsdG8ubmVidWxhLnVzZXIudjEuUGFzc2NvZGUSDQoFdmFsdWUYAiAB",
                  "KAkiJQoVQ2FuY2VsUGFzc2NvZGVSZXF1ZXN0EgwKBG5hbWUYASABKAkiSgoW",
                  "Q2FuY2VsUGFzc2NvZGVSZXNwb25zZRIwCghwYXNzY29kZRgBIAEoCzIeLnNh",
                  "bHRvLm5lYnVsYS51c2VyLnYxLlBhc3Njb2RlIj0KGkFzc2lnbkVsZWN0cm9u",
                  "aWNLZXlSZXF1ZXN0EgwKBG5hbWUYASABKAkSEQoJZGV2aWNlX2lkGAIgASgJ",
                  "IloKG0Fzc2lnbkVsZWN0cm9uaWNLZXlSZXNwb25zZRI7Cg5lbGVjdHJvbmlj",
                  "X2tleRgBIAEoCzIjLnNhbHRvLm5lYnVsYS51c2VyLnYxLkVsZWN0cm9uaWNL",
                  "ZXkiKgoaQ2FuY2VsRWxlY3Ryb25pY0tleVJlcXVlc3QSDAoEbmFtZRgBIAEo",
                  "CSJaChtDYW5jZWxFbGVjdHJvbmljS2V5UmVzcG9uc2USOwoOZWxlY3Ryb25p",
                  "Y19rZXkYASABKAsyIy5zYWx0by5uZWJ1bGEudXNlci52MS5FbGVjdHJvbmlj",
                  "S2V5IngKGkVuY29kZUVsZWN0cm9uaWNLZXlSZXF1ZXN0EgwKBG5hbWUYASAB",
                  "KAkSEQoHZW5jb2RlchgCIAEoCUgAEhkKD2VsZWN0cm9uaWNfbG9jaxgDIAEo",
                  "CUgAEhQKCmNvbnRyb2xsZXIYBCABKAlIAEIICgZkZXZpY2UiHQobRW5jb2Rl",
                  "RWxlY3Ryb25pY0tleVJlc3BvbnNlIh0KG0VuY29kZUVsZWN0cm9uaWNLZXlN",
                  "ZXRhZGF0YTLtFAoLVXNlclNlcnZpY2USUQoKQ3JlYXRlVXNlchInLnNhbHRv",
                  "Lm5lYnVsYS51c2VyLnYxLkNyZWF0ZVVzZXJSZXF1ZXN0Ghouc2FsdG8ubmVi",
                  "dWxhLnVzZXIudjEuVXNlchJLCgdHZXRVc2VyEiQuc2FsdG8ubmVidWxhLnVz",
                  "ZXIudjEuR2V0VXNlclJlcXVlc3QaGi5zYWx0by5uZWJ1bGEudXNlci52MS5V",
                  "c2VyEmgKDUJhdGNoR2V0VXNlcnMSKi5zYWx0by5uZWJ1bGEudXNlci52MS5C",
                  "YXRjaEdldFVzZXJzUmVxdWVzdBorLnNhbHRvLm5lYnVsYS51c2VyLnYxLkJh",
                  "dGNoR2V0VXNlcnNSZXNwb25zZRJcCglMaXN0VXNlcnMSJi5zYWx0by5uZWJ1",
                  "bGEudXNlci52MS5MaXN0VXNlcnNSZXF1ZXN0Gicuc2FsdG8ubmVidWxhLnVz",
                  "ZXIudjEuTGlzdFVzZXJzUmVzcG9uc2USUQoKVXBkYXRlVXNlchInLnNhbHRv",
                  "Lm5lYnVsYS51c2VyLnYxLlVwZGF0ZVVzZXJSZXF1ZXN0Ghouc2FsdG8ubmVi",
                  "dWxhLnVzZXIudjEuVXNlchJNCgpEZWxldGVVc2VyEicuc2FsdG8ubmVidWxh",
                  "LnVzZXIudjEuRGVsZXRlVXNlclJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYu",
                  "RW1wdHkSXAoJQmxvY2tVc2VyEiYuc2FsdG8ubmVidWxhLnVzZXIudjEuQmxv",
                  "Y2tVc2VyUmVxdWVzdBonLnNhbHRvLm5lYnVsYS51c2VyLnYxLkJsb2NrVXNl",
                  "clJlc3BvbnNlEmIKC1VuYmxvY2tVc2VyEiguc2FsdG8ubmVidWxhLnVzZXIu",
                  "djEuVW5ibG9ja1VzZXJSZXF1ZXN0Gikuc2FsdG8ubmVidWxhLnVzZXIudjEu",
                  "VW5ibG9ja1VzZXJSZXNwb25zZRJyChVDcmVhdGVVc2VyQWNjZXNzUmlnaHQS",
                  "Mi5zYWx0by5uZWJ1bGEudXNlci52MS5DcmVhdGVVc2VyQWNjZXNzUmlnaHRS",
                  "ZXF1ZXN0GiUuc2FsdG8ubmVidWxhLnVzZXIudjEuVXNlckFjY2Vzc1JpZ2h0",
                  "EmwKEkdldFVzZXJBY2Nlc3NSaWdodBIvLnNhbHRvLm5lYnVsYS51c2VyLnYx",
                  "LkdldFVzZXJBY2Nlc3NSaWdodFJlcXVlc3QaJS5zYWx0by5uZWJ1bGEudXNl",
                  "ci52MS5Vc2VyQWNjZXNzUmlnaHQSfQoUTGlzdFVzZXJBY2Nlc3NSaWdodHMS",
                  "MS5zYWx0by5uZWJ1bGEudXNlci52MS5MaXN0VXNlckFjY2Vzc1JpZ2h0c1Jl",
                  "cXVlc3QaMi5zYWx0by5uZWJ1bGEudXNlci52MS5MaXN0VXNlckFjY2Vzc1Jp",
                  "Z2h0c1Jlc3BvbnNlEnIKFVVwZGF0ZVVzZXJBY2Nlc3NSaWdodBIyLnNhbHRv",
                  "Lm5lYnVsYS51c2VyLnYxLlVwZGF0ZVVzZXJBY2Nlc3NSaWdodFJlcXVlc3Qa",
                  "JS5zYWx0by5uZWJ1bGEudXNlci52MS5Vc2VyQWNjZXNzUmlnaHQSYwoVRGVs",
                  "ZXRlVXNlckFjY2Vzc1JpZ2h0EjIuc2FsdG8ubmVidWxhLnVzZXIudjEuRGVs",
                  "ZXRlVXNlckFjY2Vzc1JpZ2h0UmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5F",
                  "bXB0eRJaCg1Bc3NpZ25DYXJkS2V5Eiouc2FsdG8ubmVidWxhLnVzZXIudjEu",
                  "QXNzaWduQ2FyZEtleVJlcXVlc3QaHS5zYWx0by5uZWJ1bGEudXNlci52MS5D",
                  "YXJkS2V5EloKDUNhbmNlbENhcmRLZXkSKi5zYWx0by5uZWJ1bGEudXNlci52",
                  "MS5DYW5jZWxDYXJkS2V5UmVxdWVzdBodLnNhbHRvLm5lYnVsYS51c2VyLnYx",
                  "LkNhcmRLZXkSXAoNRW5jb2RlQ2FyZEtleRIqLnNhbHRvLm5lYnVsYS51c2Vy",
                  "LnYxLkVuY29kZUNhcmRLZXlSZXF1ZXN0Gh8uc2FsdG8ubG9uZ3J1bm5pbmcu",
                  "djEuT3BlcmF0aW9uElcKDEFzc2lnbkFwcEtleRIpLnNhbHRvLm5lYnVsYS51",
                  "c2VyLnYxLkFzc2lnbkFwcEtleVJlcXVlc3QaHC5zYWx0by5uZWJ1bGEudXNl",
                  "ci52MS5BcHBLZXkSVwoMQ2FuY2VsQXBwS2V5Eikuc2FsdG8ubmVidWxhLnVz",
                  "ZXIudjEuQ2FuY2VsQXBwS2V5UmVxdWVzdBocLnNhbHRvLm5lYnVsYS51c2Vy",
                  "LnYxLkFwcEtleRJ0ChFDb21wdXRlQXBwS2V5RGF0YRIuLnNhbHRvLm5lYnVs",
                  "YS51c2VyLnYxLkNvbXB1dGVBcHBLZXlEYXRhUmVxdWVzdBovLnNhbHRvLm5l",
                  "YnVsYS51c2VyLnYxLkNvbXB1dGVBcHBLZXlEYXRhUmVzcG9uc2USbgoPQXNz",
                  "aWduV2FsbGV0S2V5Eiwuc2FsdG8ubmVidWxhLnVzZXIudjEuQXNzaWduV2Fs",
                  "bGV0S2V5UmVxdWVzdBotLnNhbHRvLm5lYnVsYS51c2VyLnYxLkFzc2lnbldh",
                  "bGxldEtleVJlc3BvbnNlEm4KD0NhbmNlbFdhbGxldEtleRIsLnNhbHRvLm5l",
                  "YnVsYS51c2VyLnYxLkNhbmNlbFdhbGxldEtleVJlcXVlc3QaLS5zYWx0by5u",
                  "ZWJ1bGEudXNlci52MS5DYW5jZWxXYWxsZXRLZXlSZXNwb25zZRJrCg5Bc3Np",
                  "Z25QYXNzY29kZRIrLnNhbHRvLm5lYnVsYS51c2VyLnYxLkFzc2lnblBhc3Nj",
                  "b2RlUmVxdWVzdBosLnNhbHRvLm5lYnVsYS51c2VyLnYxLkFzc2lnblBhc3Nj",
                  "b2RlUmVzcG9uc2USawoOQ2FuY2VsUGFzc2NvZGUSKy5zYWx0by5uZWJ1bGEu",
                  "dXNlci52MS5DYW5jZWxQYXNzY29kZVJlcXVlc3QaLC5zYWx0by5uZWJ1bGEu",
                  "dXNlci52MS5DYW5jZWxQYXNzY29kZVJlc3BvbnNlEnoKE0Fzc2lnbkVsZWN0",
                  "cm9uaWNLZXkSMC5zYWx0by5uZWJ1bGEudXNlci52MS5Bc3NpZ25FbGVjdHJv",
                  "bmljS2V5UmVxdWVzdBoxLnNhbHRvLm5lYnVsYS51c2VyLnYxLkFzc2lnbkVs",
                  "ZWN0cm9uaWNLZXlSZXNwb25zZRJ6ChNDYW5jZWxFbGVjdHJvbmljS2V5EjAu",
                  "c2FsdG8ubmVidWxhLnVzZXIudjEuQ2FuY2VsRWxlY3Ryb25pY0tleVJlcXVl",
                  "c3QaMS5zYWx0by5uZWJ1bGEudXNlci52MS5DYW5jZWxFbGVjdHJvbmljS2V5",
                  "UmVzcG9uc2USaAoTRW5jb2RlRWxlY3Ryb25pY0tleRIwLnNhbHRvLm5lYnVs",
                  "YS51c2VyLnYxLkVuY29kZUVsZWN0cm9uaWNLZXlSZXF1ZXN0Gh8uc2FsdG8u",
                  "bG9uZ3J1bm5pbmcudjEuT3BlcmF0aW9uQsgBChxjb20uc2FsdG9hcGlzLm5l",
                  "YnVsYS51c2VyLnYxQglVc2VyUHJvdG9QAVo+Z2l0aHViLmNvbS9zYWx0b2Fw",
                  "aXMtaW50ZXJuYWwvc2FsdG9hcGlzLWdvL25lYnVsYS91c2VyL3YxO3VzZXKq",
                  "AhhTYWx0b2FwaXMuTmVidWxhLlVzZXIuVjHKAhhTYWx0b2FwaXNcTmVidWxh",
                  "XFVzZXJcVjHiAiRHUEJNZXRhZGF0YVxTYWx0b2FwaXNcTmVidWxhXFVzZXJc",
                  "VjFiBnByb3RvMw=="));
            descriptor = FileDescriptor.FromGeneratedCode(descriptorData,
                [Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, Google.Protobuf.WellKnownTypes.FieldMaskReflection.Descriptor, Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, Longrunning.V1.OperationReflection.Descriptor, Type.ScheduleReflection.Descriptor,],
                new GeneratedClrTypeInfo(null, null, [
            new(typeof(User), User.Parser, ["Name", "Parent", "GivenName", "FamilyName", "DisplayName", "Email", "ActivateTime", "ExpireTime", "Photo", "PhotoUri", "CardKey", "ElectronicKey", "AppKey", "WalletKey", "Passcode", "Blocked", "Manager"], ["Parent", "FamilyName", "Email", "Photo", "Manager"], null, null, null),
            new(typeof(UserAccessRight), UserAccessRight.Parser, ["Name", "AccessRight", "DisplayName", "Schedules", "EffectiveSchedules", "ActivateTime", "ExpireTime", "Manager"], ["ActivateTime", "ExpireTime", "Manager"], null, null, null),
            new(typeof(CardKey), CardKey.Parser, ["Name", "Uid", "State", "Outdated"], null, [typeof(CardKey.Types.State)], null, null),
            new(typeof(AppKey), AppKey.Parser, ["Name", "State", "Outdated"], null, [typeof(AppKey.Types.State)], null, null),
            new(typeof(WalletKey), WalletKey.Parser, ["Name", "State", "Outdated"], null, [typeof(WalletKey.Types.State)], null, null),
            new(typeof(Passcode), Passcode.Parser, ["Name", "State"], null, [typeof(Passcode.Types.State)], null, null),
            new(typeof(ElectronicKey), ElectronicKey.Parser, ["Name", "DeviceId", "State", "Outdated"], null, [typeof(ElectronicKey.Types.State)], null, null),
            new(typeof(CreateUserRequest), CreateUserRequest.Parser, ["Parent", "UserId", "User"], ["UserId"], null, null, null),
            new(typeof(GetUserRequest), GetUserRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(BatchGetUsersRequest), BatchGetUsersRequest.Parser, ["Parent", "Names"], null, null, null, null),
            new(typeof(BatchGetUsersResponse), BatchGetUsersResponse.Parser, ["Users"], null, null, null, null),
            new(typeof(ListUsersRequest), ListUsersRequest.Parser, ["Parent", "PageSize", "PageToken", "Filter", "OrderBy"], null, null, null, null),
            new(typeof(ListUsersResponse), ListUsersResponse.Parser, ["Users", "NextPageToken", "TotalSize"], null, null, null, null),
            new(typeof(UpdateUserRequest), UpdateUserRequest.Parser, ["User", "UpdateMask"], null, null, null, null),
            new(typeof(DeleteUserRequest), DeleteUserRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(BlockUserRequest), BlockUserRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(BlockUserResponse), BlockUserResponse.Parser, null, null, null, null, null),
            new(typeof(UnblockUserRequest), UnblockUserRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(UnblockUserResponse), UnblockUserResponse.Parser, null, null, null, null, null),
            new(typeof(CreateUserAccessRightRequest), CreateUserAccessRightRequest.Parser, ["Parent", "UserAccessRight"], null, null, null, null),
            new(typeof(GetUserAccessRightRequest), GetUserAccessRightRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ListUserAccessRightsRequest), ListUserAccessRightsRequest.Parser, ["Parent", "PageSize", "PageToken", "Filter", "OrderBy"], null, null, null, null),
            new(typeof(ListUserAccessRightsResponse), ListUserAccessRightsResponse.Parser, ["UserAccessRights", "NextPageToken"], null, null, null, null),
            new(typeof(UpdateUserAccessRightRequest), UpdateUserAccessRightRequest.Parser, ["UserAccessRight", "UpdateMask"], null, null, null, null),
            new(typeof(DeleteUserAccessRightRequest), DeleteUserAccessRightRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(AssignCardKeyRequest), AssignCardKeyRequest.Parser, ["Name", "Uid"], null, null, null, null),
            new(typeof(CancelCardKeyRequest), CancelCardKeyRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(EncodeCardKeyRequest), EncodeCardKeyRequest.Parser, ["Name", "Encoder", "ElectronicLock", "Controller"], ["Device"], null, null, null),
            new(typeof(EncodeCardKeyResponse), EncodeCardKeyResponse.Parser, null, null, null, null, null),
            new(typeof(EncodeCardKeyMetadata), EncodeCardKeyMetadata.Parser, null, null, null, null, null),
            new(typeof(AssignAppKeyRequest), AssignAppKeyRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(CancelAppKeyRequest), CancelAppKeyRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ComputeAppKeyDataRequest), ComputeAppKeyDataRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ComputeAppKeyDataResponse), ComputeAppKeyDataResponse.Parser, ["Data"], null, null, null, null),
            new(typeof(AssignWalletKeyRequest), AssignWalletKeyRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(AssignWalletKeyResponse), AssignWalletKeyResponse.Parser, ["WalletKey", "AccessUri"], null, null, null, null),
            new(typeof(CancelWalletKeyRequest), CancelWalletKeyRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(CancelWalletKeyResponse), CancelWalletKeyResponse.Parser, ["WalletKey"], null, null, null, null),
            new(typeof(AssignPasscodeRequest), AssignPasscodeRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(AssignPasscodeResponse), AssignPasscodeResponse.Parser, ["Passcode", "Value"], null, null, null, null),
            new(typeof(CancelPasscodeRequest), CancelPasscodeRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(CancelPasscodeResponse), CancelPasscodeResponse.Parser, ["Passcode"], null, null, null, null),
            new(typeof(AssignElectronicKeyRequest), AssignElectronicKeyRequest.Parser, ["Name", "DeviceId"], null, null, null, null),
            new(typeof(AssignElectronicKeyResponse), AssignElectronicKeyResponse.Parser, ["ElectronicKey"], null, null, null, null),
            new(typeof(CancelElectronicKeyRequest), CancelElectronicKeyRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(CancelElectronicKeyResponse), CancelElectronicKeyResponse.Parser, ["ElectronicKey"], null, null, null, null),
            new(typeof(EncodeElectronicKeyRequest), EncodeElectronicKeyRequest.Parser, ["Name", "Encoder", "ElectronicLock", "Controller"], ["Device"], null, null, null),
            new(typeof(EncodeElectronicKeyResponse), EncodeElectronicKeyResponse.Parser, null, null, null, null, null),
            new(typeof(EncodeElectronicKeyMetadata), EncodeElectronicKeyMetadata.Parser, null, null, null, null, null)
                ]));
        }

    }


}
