using Saltoapis.Nebula.Controller.V1.Request;
using Saltoapis.Nebula.Controller.V1.Response;

namespace Saltoapis.Nebula.Controller.V1
{
    /// <summary>Holder for reflection information generated from salto/nebula/controller/v1/controller.proto</summary>
    public static partial class ControllerReflection
    {

        /// <summary>File descriptor for salto/nebula/controller/v1/controller.proto</summary>
        public static FileDescriptor Descriptor
        {
            get { return descriptor; }
        }

        private static FileDescriptor descriptor;

        static ControllerReflection()
        {
            byte[] descriptorData = System.Convert.FromBase64String(
                string.Concat(
                  "CitzYWx0by9uZWJ1bGEvY29udHJvbGxlci92MS9jb250cm9sbGVyLnByb3Rv",
                  "EhpzYWx0by5uZWJ1bGEuY29udHJvbGxlci52MRobZ29vZ2xlL3Byb3RvYnVm",
                  "L2VtcHR5LnByb3RvGiBnb29nbGUvcHJvdG9idWYvZmllbGRfbWFzay5wcm90",
                  "bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90bxokc2FsdG8vbG9u",
                  "Z3J1bm5pbmcvdjEvb3BlcmF0aW9uLnByb3RvGidzYWx0by9uZWJ1bGEvdHlw",
                  "ZS9kZXZpY2VfbWV0YWRhdGEucHJvdG8ilwMKCkNvbnRyb2xsZXISDAoEbmFt",
                  "ZRgBIAEoCRIUCgxkaXNwbGF5X25hbWUYAiABKAkSFgoJZGV2aWNlX2lkGAMg",
                  "ASgJSAGIAQESEQoHZ2F0ZXdheRgEIAEoCUgAEhIKCGV4dGVuZGVyGAUgASgJ",
                  "SAASFQoNYWNjZXNzX3BvaW50cxgGIAMoCRITCgtpbml0aWFsaXplZBgHIAEo",
                  "CBI6Cg9kZXZpY2VfbWV0YWRhdGEYCyABKAsyIS5zYWx0by5uZWJ1bGEudHlw",
                  "ZS5EZXZpY2VNZXRhZGF0YRIQCghvdXRkYXRlZBgIIAEoCBIWCgljb25uZWN0",
                  "ZWQYCSABKAhIAogBARIzCg9sYXN0X2V2ZW50X3RpbWUYCiABKAsyGi5nb29n",
                  "bGUucHJvdG9idWYuVGltZXN0YW1wEh0KEGNhcmRfa2V5X3VwZGF0ZXIYDCAB",
                  "KAhIA4gBAUIPCg1wYXJlbnRfZGV2aWNlQgwKCl9kZXZpY2VfaWRCDAoKX2Nv",
                  "bm5lY3RlZEITChFfY2FyZF9rZXlfdXBkYXRlciLOAgoPQ29udHJvbGxlclJl",
                  "bGF5EgwKBG5hbWUYASABKAkSFwoKZGlwX3N3aXRjaBgCIAEoBUgBiAEBEhAK",
                  "CHJlbGF5X2lkGAMgASgFElsKEmRlc3RpbmF0aW9uX291dHB1dBgEIAEoCzI9",
                  "LnNhbHRvLm5lYnVsYS5jb250cm9sbGVyLnYxLkNvbnRyb2xsZXJSZWxheS5E",
                  "ZXN0aW5hdGlvbk91dHB1dEgAEkQKBnN0cmlrZRgFIAEoCzIyLnNhbHRvLm5l",
                  "YnVsYS5jb250cm9sbGVyLnYxLkNvbnRyb2xsZXJSZWxheS5TdHJpa2VIABoo",
                  "ChFEZXN0aW5hdGlvbk91dHB1dBITCgtkZXN0aW5hdGlvbhgBIAEoCRoeCgZT",
                  "dHJpa2USFAoMYWNjZXNzX3BvaW50GAEgASgJQgYKBHR5cGVCDQoLX2RpcF9z",
                  "d2l0Y2gikwEKF0NyZWF0ZUNvbnRyb2xsZXJSZXF1ZXN0Eg4KBnBhcmVudBgB",
                  "IAEoCRIaCg1jb250cm9sbGVyX2lkGAIgASgJSACIAQESOgoKY29udHJvbGxl",
                  "chgDIAEoCzImLnNhbHRvLm5lYnVsYS5jb250cm9sbGVyLnYxLkNvbnRyb2xs",
                  "ZXJCEAoOX2NvbnRyb2xsZXJfaWQiJAoUR2V0Q29udHJvbGxlclJlcXVlc3QS",
                  "DAoEbmFtZRgBIAEoCSJxChZMaXN0Q29udHJvbGxlcnNSZXF1ZXN0Eg4KBnBh",
                  "cmVudBgBIAEoCRIRCglwYWdlX3NpemUYAiABKAUSEgoKcGFnZV90b2tlbhgD",
                  "IAEoCRIOCgZmaWx0ZXIYBCABKAkSEAoIb3JkZXJfYnkYBSABKAkibwoXTGlz",
                  "dENvbnRyb2xsZXJzUmVzcG9uc2USOwoLY29udHJvbGxlcnMYASADKAsyJi5z",
                  "YWx0by5uZWJ1bGEuY29udHJvbGxlci52MS5Db250cm9sbGVyEhcKD25leHRf",
                  "cGFnZV90b2tlbhgCIAEoCSKGAQoXVXBkYXRlQ29udHJvbGxlclJlcXVlc3QS",
                  "OgoKY29udHJvbGxlchgBIAEoCzImLnNhbHRvLm5lYnVsYS5jb250cm9sbGVy",
                  "LnYxLkNvbnRyb2xsZXISLwoLdXBkYXRlX21hc2sYAiABKAsyGi5nb29nbGUu",
                  "cHJvdG9idWYuRmllbGRNYXNrIicKF0RlbGV0ZUNvbnRyb2xsZXJSZXF1ZXN0",
                  "EgwKBG5hbWUYASABKAkiOAoVQmluZENvbnRyb2xsZXJSZXF1ZXN0EgwKBG5h",
                  "bWUYASABKAkSEQoJZGV2aWNlX2lkGAIgASgJIhgKFkJpbmRDb250cm9sbGVy",
                  "UmVzcG9uc2UiNgoXVW5iaW5kQ29udHJvbGxlclJlcXVlc3QSDAoEbmFtZRgB",
                  "IAEoCRINCgVmb3JjZRgCIAEoCCIaChhVbmJpbmRDb250cm9sbGVyUmVzcG9u",
                  "c2UiKwobSW5pdGlhbGl6ZUNvbnRyb2xsZXJSZXF1ZXN0EgwKBG5hbWUYASAB",
                  "KAkiHgocSW5pdGlhbGl6ZUNvbnRyb2xsZXJSZXNwb25zZSI4ChxJbml0aWFs",
                  "aXplQ29udHJvbGxlck1ldGFkYXRhEhgKEHByb2dyZXNzX3BlcmNlbnQYASAB",
                  "KAUiKgoaQ29uZmlndXJlQ29udHJvbGxlclJlcXVlc3QSDAoEbmFtZRgBIAEo",
                  "CSIdChtDb25maWd1cmVDb250cm9sbGVyUmVzcG9uc2UiNwobQ29uZmlndXJl",
                  "Q29udHJvbGxlck1ldGFkYXRhEhgKEHByb2dyZXNzX3BlcmNlbnQYASABKAUi",
                  "JgoWUmVzZXRDb250cm9sbGVyUmVxdWVzdBIMCgRuYW1lGAEgASgJIhkKF1Jl",
                  "c2V0Q29udHJvbGxlclJlc3BvbnNlIhkKF1Jlc2V0Q29udHJvbGxlck1ldGFk",
                  "YXRhIjUKH1VwZGF0ZUNvbnRyb2xsZXJGaXJtd2FyZVJlcXVlc3QSEgoKY29u",
                  "dHJvbGxlchgBIAEoCSIiCiBVcGRhdGVDb250cm9sbGVyRmlybXdhcmVSZXNw",
                  "b25zZSI8CiBVcGRhdGVDb250cm9sbGVyRmlybXdhcmVNZXRhZGF0YRIYChBw",
                  "cm9ncmVzc19wZXJjZW50GAEgASgFIjcKIUdlbmVyYXRlQXV0aG9yaXphdGlv",
                  "blRva2VuUmVxdWVzdBISCgpjb250cm9sbGVyGAEgASgJIkEKIkdlbmVyYXRl",
                  "QXV0aG9yaXphdGlvblRva2VuUmVzcG9uc2USGwoTYXV0aG9yaXphdGlvbl90",
                  "b2tlbhgBIAEoDCI4CiJHZW5lcmF0ZUZpcm13YXJlRG93bmxvYWRVcmlSZXF1",
                  "ZXN0EhIKCmNvbnRyb2xsZXIYASABKAkiSwojR2VuZXJhdGVGaXJtd2FyZURv",
                  "d25sb2FkVXJpUmVzcG9uc2USFAoMZG93bmxvYWRfdXJpGAEgASgJEg4KBmRp",
                  "Z2VzdBgCIAEoCSIlCiNHZW5lcmF0ZUZpcm13YXJlRG93bmxvYWRVcmlNZXRh",
                  "ZGF0YSKvAQocQ3JlYXRlQ29udHJvbGxlclJlbGF5UmVxdWVzdBIOCgZwYXJl",
                  "bnQYASABKAkSIAoTY29udHJvbGxlcl9yZWxheV9pZBgCIAEoCUgAiAEBEkUK",
                  "EGNvbnRyb2xsZXJfcmVsYXkYAyABKAsyKy5zYWx0by5uZWJ1bGEuY29udHJv",
                  "bGxlci52MS5Db250cm9sbGVyUmVsYXlCFgoUX2NvbnRyb2xsZXJfcmVsYXlf",
                  "aWQiKQoZR2V0Q29udHJvbGxlclJlbGF5UmVxdWVzdBIMCgRuYW1lGAEgASgJ",
                  "InYKG0xpc3RDb250cm9sbGVyUmVsYXlzUmVxdWVzdBIOCgZwYXJlbnQYASAB",
                  "KAkSEQoJcGFnZV9zaXplGAIgASgFEhIKCnBhZ2VfdG9rZW4YAyABKAkSDgoG",
                  "ZmlsdGVyGAQgASgJEhAKCG9yZGVyX2J5GAUgASgJIn8KHExpc3RDb250cm9s",
                  "bGVyUmVsYXlzUmVzcG9uc2USRgoRY29udHJvbGxlcl9yZWxheXMYASADKAsy",
                  "Ky5zYWx0by5uZWJ1bGEuY29udHJvbGxlci52MS5Db250cm9sbGVyUmVsYXkS",
                  "FwoPbmV4dF9wYWdlX3Rva2VuGAIgASgJIpYBChxVcGRhdGVDb250cm9sbGVy",
                  "UmVsYXlSZXF1ZXN0EkUKEGNvbnRyb2xsZXJfcmVsYXkYASABKAsyKy5zYWx0",
                  "by5uZWJ1bGEuY29udHJvbGxlci52MS5Db250cm9sbGVyUmVsYXkSLwoLdXBk",
                  "YXRlX21hc2sYAiABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrIiwK",
                  "HERlbGV0ZUNvbnRyb2xsZXJSZWxheVJlcXVlc3QSDAoEbmFtZRgBIAEoCSKA",
                  "AQoiQmF0Y2hEZWxldGVDb250cm9sbGVyUmVsYXlzUmVxdWVzdBIOCgZwYXJl",
                  "bnQYASABKAkSSgoIcmVxdWVzdHMYAiADKAsyOC5zYWx0by5uZWJ1bGEuY29u",
                  "dHJvbGxlci52MS5EZWxldGVDb250cm9sbGVyUmVsYXlSZXF1ZXN0IiUKI0Jh",
                  "dGNoRGVsZXRlQ29udHJvbGxlclJlbGF5c1Jlc3BvbnNlIoABCiJCYXRjaENy",
                  "ZWF0ZUNvbnRyb2xsZXJSZWxheXNSZXF1ZXN0Eg4KBnBhcmVudBgBIAEoCRJK",
                  "CghyZXF1ZXN0cxgCIAMoCzI4LnNhbHRvLm5lYnVsYS5jb250cm9sbGVyLnYx",
                  "LkNyZWF0ZUNvbnRyb2xsZXJSZWxheVJlcXVlc3QibQojQmF0Y2hDcmVhdGVD",
                  "b250cm9sbGVyUmVsYXlzUmVzcG9uc2USRgoRY29udHJvbGxlcl9yZWxheXMY",
                  "ASADKAsyKy5zYWx0by5uZWJ1bGEuY29udHJvbGxlci52MS5Db250cm9sbGVy",
                  "UmVsYXkigAEKIkJhdGNoVXBkYXRlQ29udHJvbGxlclJlbGF5c1JlcXVlc3QS",
                  "DgoGcGFyZW50GAEgASgJEkoKCHJlcXVlc3RzGAIgAygLMjguc2FsdG8ubmVi",
                  "dWxhLmNvbnRyb2xsZXIudjEuVXBkYXRlQ29udHJvbGxlclJlbGF5UmVxdWVz",
                  "dCJtCiNCYXRjaFVwZGF0ZUNvbnRyb2xsZXJSZWxheXNSZXNwb25zZRJGChFj",
                  "b250cm9sbGVyX3JlbGF5cxgBIAMoCzIrLnNhbHRvLm5lYnVsYS5jb250cm9s",
                  "bGVyLnYxLkNvbnRyb2xsZXJSZWxheTLrFAoRQ29udHJvbGxlclNlcnZpY2US",
                  "bwoQQ3JlYXRlQ29udHJvbGxlchIzLnNhbHRvLm5lYnVsYS5jb250cm9sbGVy",
                  "LnYxLkNyZWF0ZUNvbnRyb2xsZXJSZXF1ZXN0GiYuc2FsdG8ubmVidWxhLmNv",
                  "bnRyb2xsZXIudjEuQ29udHJvbGxlchJpCg1HZXRDb250cm9sbGVyEjAuc2Fs",
                  "dG8ubmVidWxhLmNvbnRyb2xsZXIudjEuR2V0Q29udHJvbGxlclJlcXVlc3Qa",
                  "Ji5zYWx0by5uZWJ1bGEuY29udHJvbGxlci52MS5Db250cm9sbGVyEnoKD0xp",
                  "c3RDb250cm9sbGVycxIyLnNhbHRvLm5lYnVsYS5jb250cm9sbGVyLnYxLkxp",
                  "c3RDb250cm9sbGVyc1JlcXVlc3QaMy5zYWx0by5uZWJ1bGEuY29udHJvbGxl",
                  "ci52MS5MaXN0Q29udHJvbGxlcnNSZXNwb25zZRJvChBVcGRhdGVDb250cm9s",
                  "bGVyEjMuc2FsdG8ubmVidWxhLmNvbnRyb2xsZXIudjEuVXBkYXRlQ29udHJv",
                  "bGxlclJlcXVlc3QaJi5zYWx0by5uZWJ1bGEuY29udHJvbGxlci52MS5Db250",
                  "cm9sbGVyEl8KEERlbGV0ZUNvbnRyb2xsZXISMy5zYWx0by5uZWJ1bGEuY29u",
                  "dHJvbGxlci52MS5EZWxldGVDb250cm9sbGVyUmVxdWVzdBoWLmdvb2dsZS5w",
                  "cm90b2J1Zi5FbXB0eRJ3Cg5CaW5kQ29udHJvbGxlchIxLnNhbHRvLm5lYnVs",
                  "YS5jb250cm9sbGVyLnYxLkJpbmRDb250cm9sbGVyUmVxdWVzdBoyLnNhbHRv",
                  "Lm5lYnVsYS5jb250cm9sbGVyLnYxLkJpbmRDb250cm9sbGVyUmVzcG9uc2US",
                  "fQoQVW5iaW5kQ29udHJvbGxlchIzLnNhbHRvLm5lYnVsYS5jb250cm9sbGVy",
                  "LnYxLlVuYmluZENvbnRyb2xsZXJSZXF1ZXN0GjQuc2FsdG8ubmVidWxhLmNv",
                  "bnRyb2xsZXIudjEuVW5iaW5kQ29udHJvbGxlclJlc3BvbnNlEnAKFEluaXRp",
                  "YWxpemVDb250cm9sbGVyEjcuc2FsdG8ubmVidWxhLmNvbnRyb2xsZXIudjEu",
                  "SW5pdGlhbGl6ZUNvbnRyb2xsZXJSZXF1ZXN0Gh8uc2FsdG8ubG9uZ3J1bm5p",
                  "bmcudjEuT3BlcmF0aW9uEm4KE0NvbmZpZ3VyZUNvbnRyb2xsZXISNi5zYWx0",
                  "by5uZWJ1bGEuY29udHJvbGxlci52MS5Db25maWd1cmVDb250cm9sbGVyUmVx",
                  "dWVzdBofLnNhbHRvLmxvbmdydW5uaW5nLnYxLk9wZXJhdGlvbhJmCg9SZXNl",
                  "dENvbnRyb2xsZXISMi5zYWx0by5uZWJ1bGEuY29udHJvbGxlci52MS5SZXNl",
                  "dENvbnRyb2xsZXJSZXF1ZXN0Gh8uc2FsdG8ubG9uZ3J1bm5pbmcudjEuT3Bl",
                  "cmF0aW9uEngKGFVwZGF0ZUNvbnRyb2xsZXJGaXJtd2FyZRI7LnNhbHRvLm5l",
                  "YnVsYS5jb250cm9sbGVyLnYxLlVwZGF0ZUNvbnRyb2xsZXJGaXJtd2FyZVJl",
                  "cXVlc3QaHy5zYWx0by5sb25ncnVubmluZy52MS5PcGVyYXRpb24SmwEKGkdl",
                  "bmVyYXRlQXV0aG9yaXphdGlvblRva2VuEj0uc2FsdG8ubmVidWxhLmNvbnRy",
                  "b2xsZXIudjEuR2VuZXJhdGVBdXRob3JpemF0aW9uVG9rZW5SZXF1ZXN0Gj4u",
                  "c2FsdG8ubmVidWxhLmNvbnRyb2xsZXIudjEuR2VuZXJhdGVBdXRob3JpemF0",
                  "aW9uVG9rZW5SZXNwb25zZRJ+ChtHZW5lcmF0ZUZpcm13YXJlRG93bmxvYWRV",
                  "cmkSPi5zYWx0by5uZWJ1bGEuY29udHJvbGxlci52MS5HZW5lcmF0ZUZpcm13",
                  "YXJlRG93bmxvYWRVcmlSZXF1ZXN0Gh8uc2FsdG8ubG9uZ3J1bm5pbmcudjEu",
                  "T3BlcmF0aW9uEn4KFUNyZWF0ZUNvbnRyb2xsZXJSZWxheRI4LnNhbHRvLm5l",
                  "YnVsYS5jb250cm9sbGVyLnYxLkNyZWF0ZUNvbnRyb2xsZXJSZWxheVJlcXVl",
                  "c3QaKy5zYWx0by5uZWJ1bGEuY29udHJvbGxlci52MS5Db250cm9sbGVyUmVs",
                  "YXkSngEKG0JhdGNoQ3JlYXRlQ29udHJvbGxlclJlbGF5cxI+LnNhbHRvLm5l",
                  "YnVsYS5jb250cm9sbGVyLnYxLkJhdGNoQ3JlYXRlQ29udHJvbGxlclJlbGF5",
                  "c1JlcXVlc3QaPy5zYWx0by5uZWJ1bGEuY29udHJvbGxlci52MS5CYXRjaENy",
                  "ZWF0ZUNvbnRyb2xsZXJSZWxheXNSZXNwb25zZRJ4ChJHZXRDb250cm9sbGVy",
                  "UmVsYXkSNS5zYWx0by5uZWJ1bGEuY29udHJvbGxlci52MS5HZXRDb250cm9s",
                  "bGVyUmVsYXlSZXF1ZXN0Gisuc2FsdG8ubmVidWxhLmNvbnRyb2xsZXIudjEu",
                  "Q29udHJvbGxlclJlbGF5EokBChRMaXN0Q29udHJvbGxlclJlbGF5cxI3LnNh",
                  "bHRvLm5lYnVsYS5jb250cm9sbGVyLnYxLkxpc3RDb250cm9sbGVyUmVsYXlz",
                  "UmVxdWVzdBo4LnNhbHRvLm5lYnVsYS5jb250cm9sbGVyLnYxLkxpc3RDb250",
                  "cm9sbGVyUmVsYXlzUmVzcG9uc2USfgoVVXBkYXRlQ29udHJvbGxlclJlbGF5",
                  "Ejguc2FsdG8ubmVidWxhLmNvbnRyb2xsZXIudjEuVXBkYXRlQ29udHJvbGxl",
                  "clJlbGF5UmVxdWVzdBorLnNhbHRvLm5lYnVsYS5jb250cm9sbGVyLnYxLkNv",
                  "bnRyb2xsZXJSZWxheRKeAQobQmF0Y2hVcGRhdGVDb250cm9sbGVyUmVsYXlz",
                  "Ej4uc2FsdG8ubmVidWxhLmNvbnRyb2xsZXIudjEuQmF0Y2hVcGRhdGVDb250",
                  "cm9sbGVyUmVsYXlzUmVxdWVzdBo/LnNhbHRvLm5lYnVsYS5jb250cm9sbGVy",
                  "LnYxLkJhdGNoVXBkYXRlQ29udHJvbGxlclJlbGF5c1Jlc3BvbnNlEmkKFURl",
                  "bGV0ZUNvbnRyb2xsZXJSZWxheRI4LnNhbHRvLm5lYnVsYS5jb250cm9sbGVy",
                  "LnYxLkRlbGV0ZUNvbnRyb2xsZXJSZWxheVJlcXVlc3QaFi5nb29nbGUucHJv",
                  "dG9idWYuRW1wdHkSngEKG0JhdGNoRGVsZXRlQ29udHJvbGxlclJlbGF5cxI+",
                  "LnNhbHRvLm5lYnVsYS5jb250cm9sbGVyLnYxLkJhdGNoRGVsZXRlQ29udHJv",
                  "bGxlclJlbGF5c1JlcXVlc3QaPy5zYWx0by5uZWJ1bGEuY29udHJvbGxlci52",
                  "MS5CYXRjaERlbGV0ZUNvbnRyb2xsZXJSZWxheXNSZXNwb25zZULyAQoiY29t",
                  "LnNhbHRvYXBpcy5uZWJ1bGEuY29udHJvbGxlci52MUIPQ29udHJvbGxlclBy",
                  "b3RvUAFaSmdpdGh1Yi5jb20vc2FsdG9hcGlzLWludGVybmFsL3NhbHRvYXBp",
                  "cy1nby9uZWJ1bGEvY29udHJvbGxlci92MTtjb250cm9sbGVyqgIeU2FsdG9h",
                  "cGlzLk5lYnVsYS5Db250cm9sbGVyLlYxygIeU2FsdG9hcGlzXE5lYnVsYVxD",
                  "b250cm9sbGVyXFYx4gIqR1BCTWV0YWRhdGFcU2FsdG9hcGlzXE5lYnVsYVxD",
                  "b250cm9sbGVyXFYxYgZwcm90bzM="));
            descriptor = FileDescriptor.FromGeneratedCode(descriptorData,
                [Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, Google.Protobuf.WellKnownTypes.FieldMaskReflection.Descriptor, Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, Longrunning.V1.OperationReflection.Descriptor, Type.DeviceMetadataReflection.Descriptor,],
                new GeneratedClrTypeInfo(null, null, [
            new(typeof(Controller), Controller.Parser, ["Name", "DisplayName", "DeviceId", "Gateway", "Extender", "AccessPoints", "Initialized", "DeviceMetadata", "Outdated", "Connected", "LastEventTime", "CardKeyUpdater"], ["ParentDevice", "DeviceId", "Connected", "CardKeyUpdater"], null, null, null),
            new(typeof(ControllerRelay), ControllerRelay.Parser, ["Name", "DipSwitch", "RelayId", "DestinationOutput", "Strike"], ["Type", "DipSwitch"], null, null, [ new(typeof(ControllerRelay.Types.DestinationOutput), ControllerRelay.Types.DestinationOutput.Parser, ["Destination"], null, null, null, null),
            new(typeof(ControllerRelay.Types.Strike), ControllerRelay.Types.Strike.Parser, ["AccessPoint"], null, null, null, null)]),
            new(typeof(CreateControllerRequest), CreateControllerRequest.Parser, ["Parent", "ControllerId", "Controller"], ["ControllerId"], null, null, null),
            new(typeof(GetControllerRequest), GetControllerRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ListControllersRequest), ListControllersRequest.Parser, ["Parent", "PageSize", "PageToken", "Filter", "OrderBy"], null, null, null, null),
            new(typeof(ListControllersResponse), ListControllersResponse.Parser, ["Controllers", "NextPageToken"], null, null, null, null),
            new(typeof(UpdateControllerRequest), UpdateControllerRequest.Parser, ["Controller", "UpdateMask"], null, null, null, null),
            new(typeof(DeleteControllerRequest), DeleteControllerRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(BindControllerRequest), BindControllerRequest.Parser, ["Name", "DeviceId"], null, null, null, null),
            new(typeof(BindControllerResponse), BindControllerResponse.Parser, null, null, null, null, null),
            new(typeof(UnbindControllerRequest), UnbindControllerRequest.Parser, ["Name", "Force"], null, null, null, null),
            new(typeof(UnbindControllerResponse), UnbindControllerResponse.Parser, null, null, null, null, null),
            new(typeof(InitializeControllerRequest), InitializeControllerRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(InitializeControllerResponse), InitializeControllerResponse.Parser, null, null, null, null, null),
            new(typeof(InitializeControllerMetadata), InitializeControllerMetadata.Parser, ["ProgressPercent"], null, null, null, null),
            new(typeof(ConfigureControllerRequest), ConfigureControllerRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ConfigureControllerResponse), ConfigureControllerResponse.Parser, null, null, null, null, null),
            new(typeof(ConfigureControllerMetadata), ConfigureControllerMetadata.Parser, ["ProgressPercent"], null, null, null, null),
            new(typeof(ResetControllerRequest), ResetControllerRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ResetControllerResponse), ResetControllerResponse.Parser, null, null, null, null, null),
            new(typeof(ResetControllerMetadata), ResetControllerMetadata.Parser, null, null, null, null, null),
            new(typeof(UpdateControllerFirmwareRequest), UpdateControllerFirmwareRequest.Parser, ["Controller"], null, null, null, null),
            new(typeof(UpdateControllerFirmwareResponse), UpdateControllerFirmwareResponse.Parser, null, null, null, null, null),
            new(typeof(UpdateControllerFirmwareMetadata), UpdateControllerFirmwareMetadata.Parser, ["ProgressPercent"], null, null, null, null),
            new(typeof(GenerateAuthorizationTokenRequest), GenerateAuthorizationTokenRequest.Parser, ["Controller"], null, null, null, null),
            new(typeof(GenerateAuthorizationTokenResponse), GenerateAuthorizationTokenResponse.Parser, ["AuthorizationToken"], null, null, null, null),
            new(typeof(GenerateFirmwareDownloadUriRequest), GenerateFirmwareDownloadUriRequest.Parser, ["Controller"], null, null, null, null),
            new(typeof(GenerateFirmwareDownloadUriResponse), GenerateFirmwareDownloadUriResponse.Parser, ["DownloadUri", "Digest"], null, null, null, null),
            new(typeof(GenerateFirmwareDownloadUriMetadata), GenerateFirmwareDownloadUriMetadata.Parser, null, null, null, null, null),
            new(typeof(CreateControllerRelayRequest), CreateControllerRelayRequest.Parser, ["Parent", "ControllerRelayId", "ControllerRelay"], ["ControllerRelayId"], null, null, null),
            new(typeof(GetControllerRelayRequest), GetControllerRelayRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ListControllerRelaysRequest), ListControllerRelaysRequest.Parser, ["Parent", "PageSize", "PageToken", "Filter", "OrderBy"], null, null, null, null),
            new(typeof(ListControllerRelaysResponse), ListControllerRelaysResponse.Parser, ["ControllerRelays", "NextPageToken"], null, null, null, null),
            new(typeof(UpdateControllerRelayRequest), UpdateControllerRelayRequest.Parser, ["ControllerRelay", "UpdateMask"], null, null, null, null),
            new(typeof(DeleteControllerRelayRequest), DeleteControllerRelayRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(BatchDeleteControllerRelaysRequest), BatchDeleteControllerRelaysRequest.Parser, ["Parent", "Requests"], null, null, null, null),
            new(typeof(BatchDeleteControllerRelaysResponse), BatchDeleteControllerRelaysResponse.Parser, null, null, null, null, null),
            new(typeof(BatchCreateControllerRelaysRequest), BatchCreateControllerRelaysRequest.Parser, ["Parent", "Requests"], null, null, null, null),
            new(typeof(BatchCreateControllerRelaysResponse), BatchCreateControllerRelaysResponse.Parser, ["ControllerRelays"], null, null, null, null),
            new(typeof(BatchUpdateControllerRelaysRequest), BatchUpdateControllerRelaysRequest.Parser, ["Parent", "Requests"], null, null, null, null),
            new(typeof(BatchUpdateControllerRelaysResponse), BatchUpdateControllerRelaysResponse.Parser, ["ControllerRelays"], null, null, null, null)
                ]));
        }

    }


}
