using Google.Protobuf.Reflection;
using Saltoapis.Nebula.Installation.V1.Request;
using Saltoapis.Nebula.Installation.V1.Response;

namespace Saltoapis.Nebula.Installation.V1
{
    /// <summary>Holder for reflection information generated from salto/nebula/installation/v1/installation.proto</summary>
    public static partial class InstallationReflection
    {

        /// <summary>File descriptor for salto/nebula/installation/v1/installation.proto</summary>
        public static FileDescriptor Descriptor
        {
            get { return descriptor; }
        }

        private static FileDescriptor descriptor;

        static InstallationReflection()
        {
            byte[] descriptorData = System.Convert.FromBase64String(
                string.Concat(
                  "Ci9zYWx0by9uZWJ1bGEvaW5zdGFsbGF0aW9uL3YxL2luc3RhbGxhdGlvbi5w",
                  "cm90bxIcc2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52MRoeZ29vZ2xlL3By",
                  "b3RvYnVmL2R1cmF0aW9uLnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHku",
                  "cHJvdG8aIGdvb2dsZS9wcm90b2J1Zi9maWVsZF9tYXNrLnByb3RvGh9nb29n",
                  "bGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvGhZzYWx0by90eXBlL2NvbG9y",
                  "LnByb3RvGhVzYWx0by90eXBlL2RhdGUucHJvdG8ihAcKDEluc3RhbGxhdGlv",
                  "bhIMCgRuYW1lGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCRISCgVwaG90",
                  "bxgDIAEoCUgAiAEBEhEKCXBob3RvX3VyaRgEIAEoCRIPCgdhZGRyZXNzGAUg",
                  "ASgJEhEKCXRpbWVfem9uZRgGIAEoCRJRCg9kaWdpdGFsX2tleV9hcnQYByAB",
                  "KAsyOC5zYWx0by5uZWJ1bGEuaW5zdGFsbGF0aW9uLnYxLkluc3RhbGxhdGlv",
                  "bi5EaWdpdGFsS2V5QXJ0EmMKGHRyYW5zZmVyX293bmVyc2hpcF9zdGF0ZRgI",
                  "IAEoCzJBLnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuSW5zdGFsbGF0",
                  "aW9uLlRyYW5zZmVyT3duZXJzaGlwU3RhdGUSLwoLZGVsZXRlX3RpbWUYDCAB",
                  "KAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wElEKDHBhcnRuZXJfaW5m",
                  "bxgJIAEoCzI2LnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuSW5zdGFs",
                  "bGF0aW9uLlBhcnRuZXJJbmZvSAGIAQESMwoKYmxvY2tfdGltZRgLIAEoCzIa",
                  "Lmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIAogBARI3ChRrZXlfcmVuZXdh",
                  "bF9kdXJhdGlvbhgKIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbhqc",
                  "AQoNRGlnaXRhbEtleUFydBIdChBiYWNrZ3JvdW5kX2ltYWdlGAEgASgJSACI",
                  "AQESHAoUYmFja2dyb3VuZF9pbWFnZV91cmkYAiABKAkSKgoKdGV4dF9jb2xv",
                  "chgDIAEoCzIRLnNhbHRvLnR5cGUuQ29sb3JIAYgBAUITChFfYmFja2dyb3Vu",
                  "ZF9pbWFnZUINCgtfdGV4dF9jb2xvchpYChZUcmFuc2Zlck93bmVyc2hpcFN0",
                  "YXRlEg0KBWVtYWlsGAEgASgJEi8KC2V4cGlyZV90aW1lGAIgASgLMhouZ29v",
                  "Z2xlLnByb3RvYnVmLlRpbWVzdGFtcBo4CgtQYXJ0bmVySW5mbxISCgpwYXJ0",
                  "bmVyX2lkGAEgASgJEhUKDWN1cnJlbmN5X2NvZGUYAiABKAlCCAoGX3Bob3Rv",
                  "Qg8KDV9wYXJ0bmVyX2luZm9CDQoLX2Jsb2NrX3RpbWUipQIKDFN1YnNjcmlw",
                  "dGlvbhIMCgRuYW1lGAEgASgJEjcKDnRyaWFsX2VuZF90aW1lGAMgASgLMhou",
                  "Z29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgAiAEBEj8KDGJpbGxpbmdfaW5m",
                  "bxgEIAEoCzIpLnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuQmlsbGlu",
                  "Z0luZm8SQwoOcGF5bWVudF9tZXRob2QYBSABKAsyKy5zYWx0by5uZWJ1bGEu",
                  "aW5zdGFsbGF0aW9uLnYxLlBheW1lbnRNZXRob2QSNQoHY291cG9ucxgGIAMo",
                  "CzIkLnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuQ291cG9uQhEKD190",
                  "cmlhbF9lbmRfdGltZSK9AQoLQmlsbGluZ0luZm8SDAoEbmFtZRgBIAEoCRIP",
                  "Cgdjb21wYW55GAIgASgJEg8KB2FkZHJlc3MYAyADKAkSEwoLcmVnaW9uX2Nv",
                  "ZGUYBCABKAkSDAoEY2l0eRgFIAEoCRIXCgpzdGF0ZV9jb2RlGAYgASgJSACI",
                  "AQESCwoDemlwGAcgASgJEhcKCnZhdF9udW1iZXIYCCABKAlIAYgBAUINCgtf",
                  "c3RhdGVfY29kZUINCgtfdmF0X251bWJlciLTAwoNUGF5bWVudE1ldGhvZBIM",
                  "CgRuYW1lGAEgASgJEkAKBGNhcmQYAiABKAsyMC5zYWx0by5uZWJ1bGEuaW5z",
                  "dGFsbGF0aW9uLnYxLlBheW1lbnRNZXRob2QuQ2FyZEgAEk8KDGRpcmVjdF9k",
                  "ZWJpdBgDIAEoCzI3LnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuUGF5",
                  "bWVudE1ldGhvZC5EaXJlY3REZWJpdEgAGm4KBENhcmQSJQoLZXhwaXJlX2Rh",
                  "dGUYASABKAsyEC5zYWx0by50eXBlLkRhdGUSEQoJbGFzdF9mb3VyGAIgASgJ",
                  "Eg0KBWJyYW5kGAMgASgJEh0KFXBheW1lbnRfYXV0aG9yaXphdGlvbhgEIAEo",
                  "CRqmAQoLRGlyZWN0RGViaXQSTAoEc2VwYRgBIAEoCzI8LnNhbHRvLm5lYnVs",
                  "YS5pbnN0YWxsYXRpb24udjEuUGF5bWVudE1ldGhvZC5EaXJlY3REZWJpdC5T",
                  "RVBBSAAaPwoEU0VQQRIRCglsYXN0X2ZvdXIYASABKAkSFgoOYWNjb3VudF9o",
                  "b2xkZXIYAiABKAkSDAoEaWJhbhgDIAEoCUIICgZzY2hlbWVCCAoGbWV0aG9k",
                  "IiQKFFBheW1lbnRBdXRob3JpemF0aW9uEgwKBG5hbWUYASABKAkiFgoGQ291",
                  "cG9uEgwKBG5hbWUYASABKAki8wIKB0ludm9pY2USDAoEbmFtZRgBIAEoCRIu",
                  "CgpzdGFydF90aW1lGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFt",
                  "cBIsCghlbmRfdGltZRgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3Rh",
                  "bXASQgoKbGluZV9pdGVtcxgEIAMoCzIuLnNhbHRvLm5lYnVsYS5pbnN0YWxs",
                  "YXRpb24udjEuSW52b2ljZS5MaW5lSXRlbRINCgV0b3RhbBgFIAEoAxI6CgVz",
                  "dGF0ZRgGIAEoDjIrLnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuSW52",
                  "b2ljZS5TdGF0ZRo3CghMaW5lSXRlbRIKCgJpZBgBIAEoCRIQCghxdWFudGl0",
                  "eRgCIAEoBRINCgVwcmljZRgDIAEoAyI0CgVTdGF0ZRIVChFTVEFURV9VTlNQ",
                  "RUNJRklFRBAAEgoKBlVOUEFJRBABEggKBFBBSUQQAiI1CgZQb2xpY3kSDAoE",
                  "bmFtZRgBIAEoCRIOCgZtZW1iZXIYAiABKAkSDQoFcm9sZXMYAyADKAkivQEK",
                  "GUNyZWF0ZUluc3RhbGxhdGlvblJlcXVlc3QSHAoPaW5zdGFsbGF0aW9uX2lk",
                  "GAEgASgJSACIAQESQAoMaW5zdGFsbGF0aW9uGAIgASgLMiouc2FsdG8ubmVi",
                  "dWxhLmluc3RhbGxhdGlvbi52MS5JbnN0YWxsYXRpb24SGgoNdmFsaWRhdGVf",
                  "b25seRgFIAEoCEgBiAEBQhIKEF9pbnN0YWxsYXRpb25faWRCEAoOX3ZhbGlk",
                  "YXRlX29ubHkiJgoWR2V0SW5zdGFsbGF0aW9uUmVxdWVzdBIMCgRuYW1lGAEg",
                  "ASgJInkKGExpc3RJbnN0YWxsYXRpb25zUmVxdWVzdBIRCglwYWdlX3NpemUY",
                  "ASABKAUSEgoKcGFnZV90b2tlbhgCIAEoCRIOCgZmaWx0ZXIYAyABKAkSEAoI",
                  "b3JkZXJfYnkYBCABKAkSFAoMc2hvd19kZWxldGVkGAUgASgIIncKGUxpc3RJ",
                  "bnN0YWxsYXRpb25zUmVzcG9uc2USQQoNaW5zdGFsbGF0aW9ucxgBIAMoCzIq",
                  "LnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuSW5zdGFsbGF0aW9uEhcK",
                  "D25leHRfcGFnZV90b2tlbhgCIAEoCSKOAQoZVXBkYXRlSW5zdGFsbGF0aW9u",
                  "UmVxdWVzdBJACgxpbnN0YWxsYXRpb24YASABKAsyKi5zYWx0by5uZWJ1bGEu",
                  "aW5zdGFsbGF0aW9uLnYxLkluc3RhbGxhdGlvbhIvCgt1cGRhdGVfbWFzaxgC",
                  "IAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE1hc2sigQEKGURlbGV0ZUlu",
                  "c3RhbGxhdGlvblJlcXVlc3QSDAoEbmFtZRgBIAEoCRIaCg12YWxpZGF0ZV9v",
                  "bmx5GAIgASgISACIAQESGAoLZGVsYXlfaG91cnMYAyABKAVIAYgBAUIQCg5f",
                  "dmFsaWRhdGVfb25seUIOCgxfZGVsYXlfaG91cnMiKwobVW5kZWxldGVJbnN0",
                  "YWxsYXRpb25SZXF1ZXN0EgwKBG5hbWUYASABKAkibgoTQ3JlYXRlUG9saWN5",
                  "UmVxdWVzdBIOCgZwYXJlbnQYASABKAkSEQoJcG9saWN5X2lkGAIgASgJEjQK",
                  "BnBvbGljeRgDIAEoCzIkLnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEu",
                  "UG9saWN5IiAKEEdldFBvbGljeVJlcXVlc3QSDAoEbmFtZRgBIAEoCSJuChNM",
                  "aXN0UG9saWNpZXNSZXF1ZXN0Eg4KBnBhcmVudBgBIAEoCRIRCglwYWdlX3Np",
                  "emUYAiABKAUSEgoKcGFnZV90b2tlbhgDIAEoCRIOCgZmaWx0ZXIYBCABKAkS",
                  "EAoIb3JkZXJfYnkYBSABKAkiZwoUTGlzdFBvbGljaWVzUmVzcG9uc2USNgoI",
                  "cG9saWNpZXMYASADKAsyJC5zYWx0by5uZWJ1bGEuaW5zdGFsbGF0aW9uLnYx",
                  "LlBvbGljeRIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkifAoTVXBkYXRlUG9s",
                  "aWN5UmVxdWVzdBI0CgZwb2xpY3kYASABKAsyJC5zYWx0by5uZWJ1bGEuaW5z",
                  "dGFsbGF0aW9uLnYxLlBvbGljeRIvCgt1cGRhdGVfbWFzaxgCIAEoCzIaLmdv",
                  "b2dsZS5wcm90b2J1Zi5GaWVsZE1hc2siIwoTRGVsZXRlUG9saWN5UmVxdWVz",
                  "dBIMCgRuYW1lGAEgASgJIkMKFlRlc3RQZXJtaXNzaW9uc1JlcXVlc3QSFAoM",
                  "aW5zdGFsbGF0aW9uGAEgASgJEhMKC3Blcm1pc3Npb25zGAIgAygJIi4KF1Rl",
                  "c3RQZXJtaXNzaW9uc1Jlc3BvbnNlEhMKC3Blcm1pc3Npb25zGAEgAygJIksK",
                  "JFRyYW5zZmVySW5zdGFsbGF0aW9uT3duZXJzaGlwUmVxdWVzdBIUCgxpbnN0",
                  "YWxsYXRpb24YASABKAkSDQoFZW1haWwYAiABKAkiJwolVHJhbnNmZXJJbnN0",
                  "YWxsYXRpb25Pd25lcnNoaXBSZXNwb25zZSKRAQoiQWNjZXB0SW5zdGFsbGF0",
                  "aW9uT3duZXJzaGlwUmVxdWVzdBIUCgxpbnN0YWxsYXRpb24YASABKAkSRAoM",
                  "YmlsbGluZ19pbmZvGAIgASgLMikuc2FsdG8ubmVidWxhLmluc3RhbGxhdGlv",
                  "bi52MS5CaWxsaW5nSW5mb0gAiAEBQg8KDV9iaWxsaW5nX2luZm8iJQojQWNj",
                  "ZXB0SW5zdGFsbGF0aW9uT3duZXJzaGlwUmVzcG9uc2UiJgoWR2V0U3Vic2Ny",
                  "aXB0aW9uUmVxdWVzdBIMCgRuYW1lGAEgASgJIlsKGFVwZGF0ZUJpbGxpbmdJ",
                  "bmZvUmVxdWVzdBI/CgxiaWxsaW5nX2luZm8YASABKAsyKS5zYWx0by5uZWJ1",
                  "bGEuaW5zdGFsbGF0aW9uLnYxLkJpbGxpbmdJbmZvImEKGlVwZGF0ZVBheW1l",
                  "bnRNZXRob2RSZXF1ZXN0EkMKDnBheW1lbnRfbWV0aG9kGAEgASgLMisuc2Fs",
                  "dG8ubmVidWxhLmluc3RhbGxhdGlvbi52MS5QYXltZW50TWV0aG9kIjoKEVVw",
                  "ZGF0ZUNhcmRSZXF1ZXN0EhYKDnBheW1lbnRfbWV0aG9kGAEgASgJEg0KBXRv",
                  "a2VuGAIgASgJIhQKElVwZGF0ZUNhcmRSZXNwb25zZSKGAQohQ3JlYXRlUGF5",
                  "bWVudEF1dGhvcml6YXRpb25SZXF1ZXN0Eg4KBnBhcmVudBgBIAEoCRJRChVw",
                  "YXltZW50X2F1dGhvcml6YXRpb24YAiABKAsyMi5zYWx0by5uZWJ1bGEuaW5z",
                  "dGFsbGF0aW9uLnYxLlBheW1lbnRBdXRob3JpemF0aW9uIiUKE0xpc3RJbnZv",
                  "aWNlc1JlcXVlc3QSDgoGcGFyZW50GAEgASgJIk8KFExpc3RJbnZvaWNlc1Jl",
                  "c3BvbnNlEjcKCGludm9pY2VzGAEgAygLMiUuc2FsdG8ubmVidWxhLmluc3Rh",
                  "bGxhdGlvbi52MS5JbnZvaWNlIjoKEkFwcGx5Q291cG9uUmVxdWVzdBIUCgxz",
                  "dWJzY3JpcHRpb24YASABKAkSDgoGY291cG9uGAIgASgJIhUKE0FwcGx5Q291",
                  "cG9uUmVzcG9uc2UiPAoUVW5hcHBseUNvdXBvblJlcXVlc3QSFAoMc3Vic2Ny",
                  "aXB0aW9uGAEgASgJEg4KBmNvdXBvbhgCIAEoCSIXChVVbmFwcGx5Q291cG9u",
                  "UmVzcG9uc2UiOQohR2VuZXJhdGVBdXRob3JpemF0aW9uVG9rZW5SZXF1ZXN0",
                  "EhQKDGluc3RhbGxhdGlvbhgBIAEoCSJBCiJHZW5lcmF0ZUF1dGhvcml6YXRp",
                  "b25Ub2tlblJlc3BvbnNlEhsKE2F1dGhvcml6YXRpb25fdG9rZW4YASABKAwy",
                  "zxYKE0luc3RhbGxhdGlvblNlcnZpY2USeQoSQ3JlYXRlSW5zdGFsbGF0aW9u",
                  "Ejcuc2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52MS5DcmVhdGVJbnN0YWxs",
                  "YXRpb25SZXF1ZXN0Giouc2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52MS5J",
                  "bnN0YWxsYXRpb24ScwoPR2V0SW5zdGFsbGF0aW9uEjQuc2FsdG8ubmVidWxh",
                  "Lmluc3RhbGxhdGlvbi52MS5HZXRJbnN0YWxsYXRpb25SZXF1ZXN0Giouc2Fs",
                  "dG8ubmVidWxhLmluc3RhbGxhdGlvbi52MS5JbnN0YWxsYXRpb24ShAEKEUxp",
                  "c3RJbnN0YWxsYXRpb25zEjYuc2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52",
                  "MS5MaXN0SW5zdGFsbGF0aW9uc1JlcXVlc3QaNy5zYWx0by5uZWJ1bGEuaW5z",
                  "dGFsbGF0aW9uLnYxLkxpc3RJbnN0YWxsYXRpb25zUmVzcG9uc2USeQoSVXBk",
                  "YXRlSW5zdGFsbGF0aW9uEjcuc2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52",
                  "MS5VcGRhdGVJbnN0YWxsYXRpb25SZXF1ZXN0Giouc2FsdG8ubmVidWxhLmlu",
                  "c3RhbGxhdGlvbi52MS5JbnN0YWxsYXRpb24SeQoSRGVsZXRlSW5zdGFsbGF0",
                  "aW9uEjcuc2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52MS5EZWxldGVJbnN0",
                  "YWxsYXRpb25SZXF1ZXN0Giouc2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52",
                  "MS5JbnN0YWxsYXRpb24SfQoUVW5kZWxldGVJbnN0YWxsYXRpb24SOS5zYWx0",
                  "by5uZWJ1bGEuaW5zdGFsbGF0aW9uLnYxLlVuZGVsZXRlSW5zdGFsbGF0aW9u",
                  "UmVxdWVzdBoqLnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuSW5zdGFs",
                  "bGF0aW9uEmcKDENyZWF0ZVBvbGljeRIxLnNhbHRvLm5lYnVsYS5pbnN0YWxs",
                  "YXRpb24udjEuQ3JlYXRlUG9saWN5UmVxdWVzdBokLnNhbHRvLm5lYnVsYS5p",
                  "bnN0YWxsYXRpb24udjEuUG9saWN5EmEKCUdldFBvbGljeRIuLnNhbHRvLm5l",
                  "YnVsYS5pbnN0YWxsYXRpb24udjEuR2V0UG9saWN5UmVxdWVzdBokLnNhbHRv",
                  "Lm5lYnVsYS5pbnN0YWxsYXRpb24udjEuUG9saWN5EnUKDExpc3RQb2xpY2ll",
                  "cxIxLnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuTGlzdFBvbGljaWVz",
                  "UmVxdWVzdBoyLnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuTGlzdFBv",
                  "bGljaWVzUmVzcG9uc2USZwoMVXBkYXRlUG9saWN5EjEuc2FsdG8ubmVidWxh",
                  "Lmluc3RhbGxhdGlvbi52MS5VcGRhdGVQb2xpY3lSZXF1ZXN0GiQuc2FsdG8u",
                  "bmVidWxhLmluc3RhbGxhdGlvbi52MS5Qb2xpY3kSWQoMRGVsZXRlUG9saWN5",
                  "EjEuc2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52MS5EZWxldGVQb2xpY3lS",
                  "ZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5En4KD1Rlc3RQZXJtaXNz",
                  "aW9ucxI0LnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuVGVzdFBlcm1p",
                  "c3Npb25zUmVxdWVzdBo1LnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEu",
                  "VGVzdFBlcm1pc3Npb25zUmVzcG9uc2USqAEKHVRyYW5zZmVySW5zdGFsbGF0",
                  "aW9uT3duZXJzaGlwEkIuc2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52MS5U",
                  "cmFuc2Zlckluc3RhbGxhdGlvbk93bmVyc2hpcFJlcXVlc3QaQy5zYWx0by5u",
                  "ZWJ1bGEuaW5zdGFsbGF0aW9uLnYxLlRyYW5zZmVySW5zdGFsbGF0aW9uT3du",
                  "ZXJzaGlwUmVzcG9uc2USogEKG0FjY2VwdEluc3RhbGxhdGlvbk93bmVyc2hp",
                  "cBJALnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuQWNjZXB0SW5zdGFs",
                  "bGF0aW9uT3duZXJzaGlwUmVxdWVzdBpBLnNhbHRvLm5lYnVsYS5pbnN0YWxs",
                  "YXRpb24udjEuQWNjZXB0SW5zdGFsbGF0aW9uT3duZXJzaGlwUmVzcG9uc2US",
                  "cwoPR2V0U3Vic2NyaXB0aW9uEjQuc2FsdG8ubmVidWxhLmluc3RhbGxhdGlv",
                  "bi52MS5HZXRTdWJzY3JpcHRpb25SZXF1ZXN0Giouc2FsdG8ubmVidWxhLmlu",
                  "c3RhbGxhdGlvbi52MS5TdWJzY3JpcHRpb24SdgoRVXBkYXRlQmlsbGluZ0lu",
                  "Zm8SNi5zYWx0by5uZWJ1bGEuaW5zdGFsbGF0aW9uLnYxLlVwZGF0ZUJpbGxp",
                  "bmdJbmZvUmVxdWVzdBopLnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEu",
                  "QmlsbGluZ0luZm8SfAoTVXBkYXRlUGF5bWVudE1ldGhvZBI4LnNhbHRvLm5l",
                  "YnVsYS5pbnN0YWxsYXRpb24udjEuVXBkYXRlUGF5bWVudE1ldGhvZFJlcXVl",
                  "c3QaKy5zYWx0by5uZWJ1bGEuaW5zdGFsbGF0aW9uLnYxLlBheW1lbnRNZXRo",
                  "b2QSbwoKVXBkYXRlQ2FyZBIvLnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24u",
                  "djEuVXBkYXRlQ2FyZFJlcXVlc3QaMC5zYWx0by5uZWJ1bGEuaW5zdGFsbGF0",
                  "aW9uLnYxLlVwZGF0ZUNhcmRSZXNwb25zZRKRAQoaQ3JlYXRlUGF5bWVudEF1",
                  "dGhvcml6YXRpb24SPy5zYWx0by5uZWJ1bGEuaW5zdGFsbGF0aW9uLnYxLkNy",
                  "ZWF0ZVBheW1lbnRBdXRob3JpemF0aW9uUmVxdWVzdBoyLnNhbHRvLm5lYnVs",
                  "YS5pbnN0YWxsYXRpb24udjEuUGF5bWVudEF1dGhvcml6YXRpb24SdQoMTGlz",
                  "dEludm9pY2VzEjEuc2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52MS5MaXN0",
                  "SW52b2ljZXNSZXF1ZXN0GjIuc2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52",
                  "MS5MaXN0SW52b2ljZXNSZXNwb25zZRJyCgtBcHBseUNvdXBvbhIwLnNhbHRv",
                  "Lm5lYnVsYS5pbnN0YWxsYXRpb24udjEuQXBwbHlDb3Vwb25SZXF1ZXN0GjEu",
                  "c2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52MS5BcHBseUNvdXBvblJlc3Bv",
                  "bnNlEngKDVVuYXBwbHlDb3Vwb24SMi5zYWx0by5uZWJ1bGEuaW5zdGFsbGF0",
                  "aW9uLnYxLlVuYXBwbHlDb3Vwb25SZXF1ZXN0GjMuc2FsdG8ubmVidWxhLmlu",
                  "c3RhbGxhdGlvbi52MS5VbmFwcGx5Q291cG9uUmVzcG9uc2USnwEKGkdlbmVy",
                  "YXRlQXV0aG9yaXphdGlvblRva2VuEj8uc2FsdG8ubmVidWxhLmluc3RhbGxh",
                  "dGlvbi52MS5HZW5lcmF0ZUF1dGhvcml6YXRpb25Ub2tlblJlcXVlc3QaQC5z",
                  "YWx0by5uZWJ1bGEuaW5zdGFsbGF0aW9uLnYxLkdlbmVyYXRlQXV0aG9yaXph",
                  "dGlvblRva2VuUmVzcG9uc2VCgAIKJGNvbS5zYWx0b2FwaXMubmVidWxhLmlu",
                  "c3RhbGxhdGlvbi52MUIRSW5zdGFsbGF0aW9uUHJvdG9QAVpOZ2l0aHViLmNv",
                  "bS9zYWx0b2FwaXMtaW50ZXJuYWwvc2FsdG9hcGlzLWdvL25lYnVsYS9pbnN0",
                  "YWxsYXRpb24vdjE7aW5zdGFsbGF0aW9uqgIgU2FsdG9hcGlzLk5lYnVsYS5J",
                  "bnN0YWxsYXRpb24uVjHKAiBTYWx0b2FwaXNcTmVidWxhXEluc3RhbGxhdGlv",
                  "blxWMeICLEdQQk1ldGFkYXRhXFNhbHRvYXBpc1xOZWJ1bGFcSW5zdGFsbGF0",
                  "aW9uXFYxYgZwcm90bzM="));
            descriptor = FileDescriptor.FromGeneratedCode(descriptorData,
                [Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, Google.Protobuf.WellKnownTypes.FieldMaskReflection.Descriptor, Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, Type.ColorReflection.Descriptor, Type.DateReflection.Descriptor,],
                new GeneratedClrTypeInfo(null, null, [
            new(typeof(Installation), Installation.Parser, ["Name", "DisplayName", "Photo", "PhotoUri", "Address", "TimeZone", "DigitalKeyArt", "TransferOwnershipState", "DeleteTime", "PartnerInfo", "BlockTime", "KeyRenewalDuration"], ["Photo", "PartnerInfo", "BlockTime"], null, null, [ new(typeof(Installation.Types.DigitalKeyArt), Installation.Types.DigitalKeyArt.Parser, ["BackgroundImage", "BackgroundImageUri", "TextColor"], ["BackgroundImage", "TextColor"], null, null, null),
            new(typeof(Installation.Types.TransferOwnershipState), Installation.Types.TransferOwnershipState.Parser, ["Email", "ExpireTime"], null, null, null, null),
            new(typeof(Installation.Types.PartnerInfo), Installation.Types.PartnerInfo.Parser, ["PartnerId", "CurrencyCode"], null, null, null, null)]),
            new(typeof(Subscription), Subscription.Parser, ["Name", "TrialEndTime", "BillingInfo", "PaymentMethod", "Coupons"], ["TrialEndTime"], null, null, null),
            new(typeof(BillingInfo), BillingInfo.Parser, ["Name", "Company", "Address", "RegionCode", "City", "StateCode", "Zip", "VatNumber"], ["StateCode", "VatNumber"], null, null, null),
            new(typeof(PaymentMethod), PaymentMethod.Parser, ["Name", "Card", "DirectDebit"], ["Method"], null, null, [ new(typeof(PaymentMethod.Types.Card), PaymentMethod.Types.Card.Parser, ["ExpireDate", "LastFour", "Brand", "PaymentAuthorization"], null, null, null, null),
            new(typeof(PaymentMethod.Types.DirectDebit), PaymentMethod.Types.DirectDebit.Parser, ["Sepa"], ["Scheme"], null, null, [new(typeof(PaymentMethod.Types.DirectDebit.Types.SEPA), PaymentMethod.Types.DirectDebit.Types.SEPA.Parser, ["LastFour", "AccountHolder", "Iban"], null, null, null, null)])]),
            new(typeof(PaymentAuthorization), PaymentAuthorization.Parser, ["Name"], null, null, null, null),
            new(typeof(Coupon), Coupon.Parser, ["Name"], null, null, null, null),
            new(typeof(Invoice), Invoice.Parser, ["Name", "StartTime", "EndTime", "LineItems", "Total", "State"], null, [typeof(Invoice.Types.State)], null, [new(typeof(Invoice.Types.LineItem), Invoice.Types.LineItem.Parser, ["Id", "Quantity", "Price"], null, null, null, null)]),
            new(typeof(Policy), Policy.Parser, ["Name", "Member", "Roles"], null, null, null, null),
            new(typeof(CreateInstallationRequest), CreateInstallationRequest.Parser, ["InstallationId", "Installation", "ValidateOnly"], ["InstallationId", "ValidateOnly"], null, null, null),
            new(typeof(GetInstallationRequest), GetInstallationRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ListInstallationsRequest), ListInstallationsRequest.Parser, ["PageSize", "PageToken", "Filter", "OrderBy", "ShowDeleted"], null, null, null, null),
            new(typeof(ListInstallationsResponse), ListInstallationsResponse.Parser, ["Installations", "NextPageToken"], null, null, null, null),
            new(typeof(UpdateInstallationRequest), UpdateInstallationRequest.Parser, ["Installation", "UpdateMask"], null, null, null, null),
            new(typeof(DeleteInstallationRequest), DeleteInstallationRequest.Parser, ["Name", "ValidateOnly", "DelayHours"], ["ValidateOnly", "DelayHours"], null, null, null),
            new(typeof(UndeleteInstallationRequest), UndeleteInstallationRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(CreatePolicyRequest), CreatePolicyRequest.Parser, ["Parent", "PolicyId", "Policy"], null, null, null, null),
            new(typeof(GetPolicyRequest), GetPolicyRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ListPoliciesRequest), ListPoliciesRequest.Parser, ["Parent", "PageSize", "PageToken", "Filter", "OrderBy"], null, null, null, null),
            new(typeof(ListPoliciesResponse), ListPoliciesResponse.Parser, ["Policies", "NextPageToken"], null, null, null, null),
            new(typeof(UpdatePolicyRequest), UpdatePolicyRequest.Parser, ["Policy", "UpdateMask"], null, null, null, null),
            new(typeof(DeletePolicyRequest), DeletePolicyRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(TestPermissionsRequest), TestPermissionsRequest.Parser, ["Installation", "Permissions"], null, null, null, null),
            new(typeof(TestPermissionsResponse), TestPermissionsResponse.Parser, ["Permissions"], null, null, null, null),
            new(typeof(TransferInstallationOwnershipRequest), TransferInstallationOwnershipRequest.Parser, ["Installation", "Email"], null, null, null, null),
            new(typeof(TransferInstallationOwnershipResponse), TransferInstallationOwnershipResponse.Parser, null, null, null, null, null),
            new(typeof(AcceptInstallationOwnershipRequest), AcceptInstallationOwnershipRequest.Parser, ["Installation", "BillingInfo"], ["BillingInfo"], null, null, null),
            new(typeof(AcceptInstallationOwnershipResponse), AcceptInstallationOwnershipResponse.Parser, null, null, null, null, null),
            new(typeof(GetSubscriptionRequest), GetSubscriptionRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(UpdateBillingInfoRequest), UpdateBillingInfoRequest.Parser, ["BillingInfo"], null, null, null, null),
            new(typeof(UpdatePaymentMethodRequest), UpdatePaymentMethodRequest.Parser, ["PaymentMethod"], null, null, null, null),
            new(typeof(UpdateCardRequest), UpdateCardRequest.Parser, ["PaymentMethod", "Token"], null, null, null, null),
            new(typeof(UpdateCardResponse), UpdateCardResponse.Parser, null, null, null, null, null),
            new(typeof(CreatePaymentAuthorizationRequest), CreatePaymentAuthorizationRequest.Parser, ["Parent", "PaymentAuthorization"], null, null, null, null),
            new(typeof(ListInvoicesRequest), ListInvoicesRequest.Parser, ["Parent"], null, null, null, null),
            new(typeof(ListInvoicesResponse), ListInvoicesResponse.Parser, ["Invoices"], null, null, null, null),
            new(typeof(ApplyCouponRequest), ApplyCouponRequest.Parser, ["Subscription", "Coupon"], null, null, null, null),
            new(typeof(ApplyCouponResponse), ApplyCouponResponse.Parser, null, null, null, null, null),
            new(typeof(UnapplyCouponRequest), UnapplyCouponRequest.Parser, ["Subscription", "Coupon"], null, null, null, null),
            new(typeof(UnapplyCouponResponse), UnapplyCouponResponse.Parser, null, null, null, null, null),
            new(typeof(GenerateAuthorizationTokenRequest), GenerateAuthorizationTokenRequest.Parser, ["Installation"], null, null, null, null),
            new(typeof(GenerateAuthorizationTokenResponse), GenerateAuthorizationTokenResponse.Parser, ["AuthorizationToken"], null, null, null, null)
                ]));
        }

    }


}
