using Saltoapis.Nebula.AccessRight.V1.Request;
using Saltoapis.Nebula.AccessRight.V1.Response;

namespace Saltoapis.Nebula.AccessRight.V1
{
    /// <summary>Holder for reflection information generated from salto/nebula/accessright/v1/access_right.proto</summary>
    public static partial class AccessRightReflection
    {
        /// <summary>File descriptor for salto/nebula/accessright/v1/access_right.proto</summary>
        public static FileDescriptor Descriptor
        {
            get => descriptor;}

        private static FileDescriptor descriptor;

        static AccessRightReflection()
        {
            byte[] descriptorData = Convert.FromBase64String(
                string.Concat(
                  "Ci5zYWx0by9uZWJ1bGEvYWNjZXNzcmlnaHQvdjEvYWNjZXNzX3JpZ2h0LnBy",
                  "b3RvEhtzYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEaG2dvb2dsZS9wcm90",
                  "b2J1Zi9lbXB0eS5wcm90bxogZ29vZ2xlL3Byb3RvYnVmL2ZpZWxkX21hc2su",
                  "cHJvdG8aIHNhbHRvL25lYnVsYS90eXBlL3NjaGVkdWxlLnByb3RvImEKC0Fj",
                  "Y2Vzc1JpZ2h0EgwKBG5hbWUYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJ",
                  "Ei4KCXNjaGVkdWxlcxgFIAMoCzIbLnNhbHRvLm5lYnVsYS50eXBlLlNjaGVk",
                  "dWxlIlIKFkFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnQSDAoEbmFtZRgBIAEoCRIU",
                  "CgxhY2Nlc3NfcG9pbnQYAiABKAkSFAoMZGlzcGxheV9uYW1lGAMgASgJIl0K",
                  "G0FjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRHcm91cBIMCgRuYW1lGAEgASgJEhoK",
                  "EmFjY2Vzc19wb2ludF9ncm91cBgCIAEoCRIUCgxkaXNwbGF5X25hbWUYAyAB",
                  "KAkiUQoWQWNjZXNzUmlnaHREZXN0aW5hdGlvbhIMCgRuYW1lGAEgASgJEhMK",
                  "C2Rlc3RpbmF0aW9uGAIgASgJEhQKDGRpc3BsYXlfbmFtZRgDIAEoCSKcAQoY",
                  "Q3JlYXRlQWNjZXNzUmlnaHRSZXF1ZXN0Eg4KBnBhcmVudBgBIAEoCRIcCg9h",
                  "Y2Nlc3NfcmlnaHRfaWQYAiABKAlIAIgBARI+CgxhY2Nlc3NfcmlnaHQYAyAB",
                  "KAsyKC5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuQWNjZXNzUmlnaHRC",
                  "EgoQX2FjY2Vzc19yaWdodF9pZCIlChVHZXRBY2Nlc3NSaWdodFJlcXVlc3QS",
                  "DAoEbmFtZRgBIAEoCSJyChdMaXN0QWNjZXNzUmlnaHRzUmVxdWVzdBIOCgZw",
                  "YXJlbnQYASABKAkSEQoJcGFnZV9zaXplGAIgASgFEhIKCnBhZ2VfdG9rZW4Y",
                  "AyABKAkSDgoGZmlsdGVyGAQgASgJEhAKCG9yZGVyX2J5GAUgASgJInQKGExp",
                  "c3RBY2Nlc3NSaWdodHNSZXNwb25zZRI/Cg1hY2Nlc3NfcmlnaHRzGAEgAygL",
                  "Miguc2FsdG8ubmVidWxhLmFjY2Vzc3JpZ2h0LnYxLkFjY2Vzc1JpZ2h0EhcK",
                  "D25leHRfcGFnZV90b2tlbhgCIAEoCSKLAQoYVXBkYXRlQWNjZXNzUmlnaHRS",
                  "ZXF1ZXN0Ej4KDGFjY2Vzc19yaWdodBgBIAEoCzIoLnNhbHRvLm5lYnVsYS5h",
                  "Y2Nlc3NyaWdodC52MS5BY2Nlc3NSaWdodBIvCgt1cGRhdGVfbWFzaxgCIAEo",
                  "CzIaLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE1hc2siKAoYRGVsZXRlQWNjZXNz",
                  "UmlnaHRSZXF1ZXN0EgwKBG5hbWUYASABKAkijQEKI0NyZWF0ZUFjY2Vzc1Jp",
                  "Z2h0QWNjZXNzUG9pbnRSZXF1ZXN0Eg4KBnBhcmVudBgBIAEoCRJWChlhY2Nl",
                  "c3NfcmlnaHRfYWNjZXNzX3BvaW50GAIgASgLMjMuc2FsdG8ubmVidWxhLmFj",
                  "Y2Vzc3JpZ2h0LnYxLkFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnQijwEKKUJhdGNo",
                  "Q3JlYXRlQWNjZXNzUmlnaHRBY2Nlc3NQb2ludHNSZXF1ZXN0Eg4KBnBhcmVu",
                  "dBgBIAEoCRJSCghyZXF1ZXN0cxgCIAMoCzJALnNhbHRvLm5lYnVsYS5hY2Nl",
                  "c3NyaWdodC52MS5DcmVhdGVBY2Nlc3NSaWdodEFjY2Vzc1BvaW50UmVxdWVz",
                  "dCKFAQoqQmF0Y2hDcmVhdGVBY2Nlc3NSaWdodEFjY2Vzc1BvaW50c1Jlc3Bv",
                  "bnNlElcKGmFjY2Vzc19yaWdodF9hY2Nlc3NfcG9pbnRzGAEgAygLMjMuc2Fs",
                  "dG8ubmVidWxhLmFjY2Vzc3JpZ2h0LnYxLkFjY2Vzc1JpZ2h0QWNjZXNzUG9p",
                  "bnQiMAogR2V0QWNjZXNzUmlnaHRBY2Nlc3NQb2ludFJlcXVlc3QSDAoEbmFt",
                  "ZRgBIAEoCSJ9CiJMaXN0QWNjZXNzUmlnaHRBY2Nlc3NQb2ludHNSZXF1ZXN0",
                  "Eg4KBnBhcmVudBgBIAEoCRIRCglwYWdlX3NpemUYAiABKAUSEgoKcGFnZV90",
                  "b2tlbhgDIAEoCRIOCgZmaWx0ZXIYBCABKAkSEAoIb3JkZXJfYnkYBSABKAki",
                  "lwEKI0xpc3RBY2Nlc3NSaWdodEFjY2Vzc1BvaW50c1Jlc3BvbnNlElcKGmFj",
                  "Y2Vzc19yaWdodF9hY2Nlc3NfcG9pbnRzGAEgAygLMjMuc2FsdG8ubmVidWxh",
                  "LmFjY2Vzc3JpZ2h0LnYxLkFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnQSFwoPbmV4",
                  "dF9wYWdlX3Rva2VuGAIgASgJIq4BCiNVcGRhdGVBY2Nlc3NSaWdodEFjY2Vz",
                  "c1BvaW50UmVxdWVzdBJWChlhY2Nlc3NfcmlnaHRfYWNjZXNzX3BvaW50GAEg",
                  "ASgLMjMuc2FsdG8ubmVidWxhLmFjY2Vzc3JpZ2h0LnYxLkFjY2Vzc1JpZ2h0",
                  "QWNjZXNzUG9pbnQSLwoLdXBkYXRlX21hc2sYAiABKAsyGi5nb29nbGUucHJv",
                  "dG9idWYuRmllbGRNYXNrIjMKI0RlbGV0ZUFjY2Vzc1JpZ2h0QWNjZXNzUG9p",
                  "bnRSZXF1ZXN0EgwKBG5hbWUYASABKAkinQEKKENyZWF0ZUFjY2Vzc1JpZ2h0",
                  "QWNjZXNzUG9pbnRHcm91cFJlcXVlc3QSDgoGcGFyZW50GAEgASgJEmEKH2Fj",
                  "Y2Vzc19yaWdodF9hY2Nlc3NfcG9pbnRfZ3JvdXAYAiABKAsyOC5zYWx0by5u",
                  "ZWJ1bGEuYWNjZXNzcmlnaHQudjEuQWNjZXNzUmlnaHRBY2Nlc3NQb2ludEdy",
                  "b3VwIpkBCi5CYXRjaENyZWF0ZUFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRHcm91",
                  "cHNSZXF1ZXN0Eg4KBnBhcmVudBgBIAEoCRJXCghyZXF1ZXN0cxgCIAMoCzJF",
                  "LnNhbHRvLm5lYnVsYS5hY2Nlc3NyaWdodC52MS5DcmVhdGVBY2Nlc3NSaWdo",
                  "dEFjY2Vzc1BvaW50R3JvdXBSZXF1ZXN0IpUBCi9CYXRjaENyZWF0ZUFjY2Vz",
                  "c1JpZ2h0QWNjZXNzUG9pbnRHcm91cHNSZXNwb25zZRJiCiBhY2Nlc3Nfcmln",
                  "aHRfYWNjZXNzX3BvaW50X2dyb3VwcxgBIAMoCzI4LnNhbHRvLm5lYnVsYS5h",
                  "Y2Nlc3NyaWdodC52MS5BY2Nlc3NSaWdodEFjY2Vzc1BvaW50R3JvdXAiNQol",
                  "R2V0QWNjZXNzUmlnaHRBY2Nlc3NQb2ludEdyb3VwUmVxdWVzdBIMCgRuYW1l",
                  "GAEgASgJIoIBCidMaXN0QWNjZXNzUmlnaHRBY2Nlc3NQb2ludEdyb3Vwc1Jl",
                  "cXVlc3QSDgoGcGFyZW50GAEgASgJEhEKCXBhZ2Vfc2l6ZRgCIAEoBRISCgpw",
                  "YWdlX3Rva2VuGAMgASgJEg4KBmZpbHRlchgEIAEoCRIQCghvcmRlcl9ieRgF",
                  "IAEoCSKnAQooTGlzdEFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRHcm91cHNSZXNw",
                  "b25zZRJiCiBhY2Nlc3NfcmlnaHRfYWNjZXNzX3BvaW50X2dyb3VwcxgBIAMo",
                  "CzI4LnNhbHRvLm5lYnVsYS5hY2Nlc3NyaWdodC52MS5BY2Nlc3NSaWdodEFj",
                  "Y2Vzc1BvaW50R3JvdXASFwoPbmV4dF9wYWdlX3Rva2VuGAIgASgJIr4BCihV",
                  "cGRhdGVBY2Nlc3NSaWdodEFjY2Vzc1BvaW50R3JvdXBSZXF1ZXN0EmEKH2Fj",
                  "Y2Vzc19yaWdodF9hY2Nlc3NfcG9pbnRfZ3JvdXAYASABKAsyOC5zYWx0by5u",
                  "ZWJ1bGEuYWNjZXNzcmlnaHQudjEuQWNjZXNzUmlnaHRBY2Nlc3NQb2ludEdy",
                  "b3VwEi8KC3VwZGF0ZV9tYXNrGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkZp",
                  "ZWxkTWFzayI4CihEZWxldGVBY2Nlc3NSaWdodEFjY2Vzc1BvaW50R3JvdXBS",
                  "ZXF1ZXN0EgwKBG5hbWUYASABKAkimQEKLkJhdGNoRGVsZXRlQWNjZXNzUmln",
                  "aHRBY2Nlc3NQb2ludEdyb3Vwc1JlcXVlc3QSDgoGcGFyZW50GAEgASgJElcK",
                  "CHJlcXVlc3RzGAIgAygLMkUuc2FsdG8ubmVidWxhLmFjY2Vzc3JpZ2h0LnYx",
                  "LkRlbGV0ZUFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRHcm91cFJlcXVlc3QiMQov",
                  "QmF0Y2hEZWxldGVBY2Nlc3NSaWdodEFjY2Vzc1BvaW50R3JvdXBzUmVzcG9u",
                  "c2UijwEKKUJhdGNoRGVsZXRlQWNjZXNzUmlnaHRBY2Nlc3NQb2ludHNSZXF1",
                  "ZXN0Eg4KBnBhcmVudBgBIAEoCRJSCghyZXF1ZXN0cxgCIAMoCzJALnNhbHRv",
                  "Lm5lYnVsYS5hY2Nlc3NyaWdodC52MS5EZWxldGVBY2Nlc3NSaWdodEFjY2Vz",
                  "c1BvaW50UmVxdWVzdCIsCipCYXRjaERlbGV0ZUFjY2Vzc1JpZ2h0QWNjZXNz",
                  "UG9pbnRzUmVzcG9uc2UijAEKI0NyZWF0ZUFjY2Vzc1JpZ2h0RGVzdGluYXRp",
                  "b25SZXF1ZXN0Eg4KBnBhcmVudBgBIAEoCRJVChhhY2Nlc3NfcmlnaHRfZGVz",
                  "dGluYXRpb24YAiABKAsyMy5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEu",
                  "QWNjZXNzUmlnaHREZXN0aW5hdGlvbiIwCiBHZXRBY2Nlc3NSaWdodERlc3Rp",
                  "bmF0aW9uUmVxdWVzdBIMCgRuYW1lGAEgASgJIn0KIkxpc3RBY2Nlc3NSaWdo",
                  "dERlc3RpbmF0aW9uc1JlcXVlc3QSDgoGcGFyZW50GAEgASgJEhEKCXBhZ2Vf",
                  "c2l6ZRgCIAEoBRISCgpwYWdlX3Rva2VuGAMgASgJEg4KBmZpbHRlchgEIAEo",
                  "CRIQCghvcmRlcl9ieRgFIAEoCSKWAQojTGlzdEFjY2Vzc1JpZ2h0RGVzdGlu",
                  "YXRpb25zUmVzcG9uc2USVgoZYWNjZXNzX3JpZ2h0X2Rlc3RpbmF0aW9ucxgB",
                  "IAMoCzIzLnNhbHRvLm5lYnVsYS5hY2Nlc3NyaWdodC52MS5BY2Nlc3NSaWdo",
                  "dERlc3RpbmF0aW9uEhcKD25leHRfcGFnZV90b2tlbhgCIAEoCSKtAQojVXBk",
                  "YXRlQWNjZXNzUmlnaHREZXN0aW5hdGlvblJlcXVlc3QSVQoYYWNjZXNzX3Jp",
                  "Z2h0X2Rlc3RpbmF0aW9uGAEgASgLMjMuc2FsdG8ubmVidWxhLmFjY2Vzc3Jp",
                  "Z2h0LnYxLkFjY2Vzc1JpZ2h0RGVzdGluYXRpb24SLwoLdXBkYXRlX21hc2sY",
                  "AiABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrIjMKI0RlbGV0ZUFj",
                  "Y2Vzc1JpZ2h0RGVzdGluYXRpb25SZXF1ZXN0EgwKBG5hbWUYASABKAkytxwK",
                  "EkFjY2Vzc1JpZ2h0U2VydmljZRJ0ChFDcmVhdGVBY2Nlc3NSaWdodBI1LnNh",
                  "bHRvLm5lYnVsYS5hY2Nlc3NyaWdodC52MS5DcmVhdGVBY2Nlc3NSaWdodFJl",
                  "cXVlc3QaKC5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuQWNjZXNzUmln",
                  "aHQSbgoOR2V0QWNjZXNzUmlnaHQSMi5zYWx0by5uZWJ1bGEuYWNjZXNzcmln",
                  "aHQudjEuR2V0QWNjZXNzUmlnaHRSZXF1ZXN0Giguc2FsdG8ubmVidWxhLmFj",
                  "Y2Vzc3JpZ2h0LnYxLkFjY2Vzc1JpZ2h0En8KEExpc3RBY2Nlc3NSaWdodHMS",
                  "NC5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuTGlzdEFjY2Vzc1JpZ2h0",
                  "c1JlcXVlc3QaNS5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuTGlzdEFj",
                  "Y2Vzc1JpZ2h0c1Jlc3BvbnNlEnQKEVVwZGF0ZUFjY2Vzc1JpZ2h0EjUuc2Fs",
                  "dG8ubmVidWxhLmFjY2Vzc3JpZ2h0LnYxLlVwZGF0ZUFjY2Vzc1JpZ2h0UmVx",
                  "dWVzdBooLnNhbHRvLm5lYnVsYS5hY2Nlc3NyaWdodC52MS5BY2Nlc3NSaWdo",
                  "dBJiChFEZWxldGVBY2Nlc3NSaWdodBI1LnNhbHRvLm5lYnVsYS5hY2Nlc3Ny",
                  "aWdodC52MS5EZWxldGVBY2Nlc3NSaWdodFJlcXVlc3QaFi5nb29nbGUucHJv",
                  "dG9idWYuRW1wdHkSlQEKHENyZWF0ZUFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnQS",
                  "QC5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuQ3JlYXRlQWNjZXNzUmln",
                  "aHRBY2Nlc3NQb2ludFJlcXVlc3QaMy5zYWx0by5uZWJ1bGEuYWNjZXNzcmln",
                  "aHQudjEuQWNjZXNzUmlnaHRBY2Nlc3NQb2ludBK1AQoiQmF0Y2hDcmVhdGVB",
                  "Y2Nlc3NSaWdodEFjY2Vzc1BvaW50cxJGLnNhbHRvLm5lYnVsYS5hY2Nlc3Ny",
                  "aWdodC52MS5CYXRjaENyZWF0ZUFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRzUmVx",
                  "dWVzdBpHLnNhbHRvLm5lYnVsYS5hY2Nlc3NyaWdodC52MS5CYXRjaENyZWF0",
                  "ZUFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRzUmVzcG9uc2USjwEKGUdldEFjY2Vz",
                  "c1JpZ2h0QWNjZXNzUG9pbnQSPS5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQu",
                  "djEuR2V0QWNjZXNzUmlnaHRBY2Nlc3NQb2ludFJlcXVlc3QaMy5zYWx0by5u",
                  "ZWJ1bGEuYWNjZXNzcmlnaHQudjEuQWNjZXNzUmlnaHRBY2Nlc3NQb2ludBKg",
                  "AQobTGlzdEFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRzEj8uc2FsdG8ubmVidWxh",
                  "LmFjY2Vzc3JpZ2h0LnYxLkxpc3RBY2Nlc3NSaWdodEFjY2Vzc1BvaW50c1Jl",
                  "cXVlc3QaQC5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuTGlzdEFjY2Vz",
                  "c1JpZ2h0QWNjZXNzUG9pbnRzUmVzcG9uc2USlQEKHFVwZGF0ZUFjY2Vzc1Jp",
                  "Z2h0QWNjZXNzUG9pbnQSQC5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEu",
                  "VXBkYXRlQWNjZXNzUmlnaHRBY2Nlc3NQb2ludFJlcXVlc3QaMy5zYWx0by5u",
                  "ZWJ1bGEuYWNjZXNzcmlnaHQudjEuQWNjZXNzUmlnaHRBY2Nlc3NQb2ludBJ4",
                  "ChxEZWxldGVBY2Nlc3NSaWdodEFjY2Vzc1BvaW50EkAuc2FsdG8ubmVidWxh",
                  "LmFjY2Vzc3JpZ2h0LnYxLkRlbGV0ZUFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRS",
                  "ZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5ErUBCiJCYXRjaERlbGV0",
                  "ZUFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRzEkYuc2FsdG8ubmVidWxhLmFjY2Vz",
                  "c3JpZ2h0LnYxLkJhdGNoRGVsZXRlQWNjZXNzUmlnaHRBY2Nlc3NQb2ludHNS",
                  "ZXF1ZXN0Gkcuc2FsdG8ubmVidWxhLmFjY2Vzc3JpZ2h0LnYxLkJhdGNoRGVs",
                  "ZXRlQWNjZXNzUmlnaHRBY2Nlc3NQb2ludHNSZXNwb25zZRKkAQohQ3JlYXRl",
                  "QWNjZXNzUmlnaHRBY2Nlc3NQb2ludEdyb3VwEkUuc2FsdG8ubmVidWxhLmFj",
                  "Y2Vzc3JpZ2h0LnYxLkNyZWF0ZUFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRHcm91",
                  "cFJlcXVlc3QaOC5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuQWNjZXNz",
                  "UmlnaHRBY2Nlc3NQb2ludEdyb3VwEsQBCidCYXRjaENyZWF0ZUFjY2Vzc1Jp",
                  "Z2h0QWNjZXNzUG9pbnRHcm91cHMSSy5zYWx0by5uZWJ1bGEuYWNjZXNzcmln",
                  "aHQudjEuQmF0Y2hDcmVhdGVBY2Nlc3NSaWdodEFjY2Vzc1BvaW50R3JvdXBz",
                  "UmVxdWVzdBpMLnNhbHRvLm5lYnVsYS5hY2Nlc3NyaWdodC52MS5CYXRjaENy",
                  "ZWF0ZUFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRHcm91cHNSZXNwb25zZRKeAQoe",
                  "R2V0QWNjZXNzUmlnaHRBY2Nlc3NQb2ludEdyb3VwEkIuc2FsdG8ubmVidWxh",
                  "LmFjY2Vzc3JpZ2h0LnYxLkdldEFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRHcm91",
                  "cFJlcXVlc3QaOC5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuQWNjZXNz",
                  "UmlnaHRBY2Nlc3NQb2ludEdyb3VwEq8BCiBMaXN0QWNjZXNzUmlnaHRBY2Nl",
                  "c3NQb2ludEdyb3VwcxJELnNhbHRvLm5lYnVsYS5hY2Nlc3NyaWdodC52MS5M",
                  "aXN0QWNjZXNzUmlnaHRBY2Nlc3NQb2ludEdyb3Vwc1JlcXVlc3QaRS5zYWx0",
                  "by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuTGlzdEFjY2Vzc1JpZ2h0QWNjZXNz",
                  "UG9pbnRHcm91cHNSZXNwb25zZRKkAQohVXBkYXRlQWNjZXNzUmlnaHRBY2Nl",
                  "c3NQb2ludEdyb3VwEkUuc2FsdG8ubmVidWxhLmFjY2Vzc3JpZ2h0LnYxLlVw",
                  "ZGF0ZUFjY2Vzc1JpZ2h0QWNjZXNzUG9pbnRHcm91cFJlcXVlc3QaOC5zYWx0",
                  "by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuQWNjZXNzUmlnaHRBY2Nlc3NQb2lu",
                  "dEdyb3VwEoIBCiFEZWxldGVBY2Nlc3NSaWdodEFjY2Vzc1BvaW50R3JvdXAS",
                  "RS5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuRGVsZXRlQWNjZXNzUmln",
                  "aHRBY2Nlc3NQb2ludEdyb3VwUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5F",
                  "bXB0eRLEAQonQmF0Y2hEZWxldGVBY2Nlc3NSaWdodEFjY2Vzc1BvaW50R3Jv",
                  "dXBzEksuc2FsdG8ubmVidWxhLmFjY2Vzc3JpZ2h0LnYxLkJhdGNoRGVsZXRl",
                  "QWNjZXNzUmlnaHRBY2Nlc3NQb2ludEdyb3Vwc1JlcXVlc3QaTC5zYWx0by5u",
                  "ZWJ1bGEuYWNjZXNzcmlnaHQudjEuQmF0Y2hEZWxldGVBY2Nlc3NSaWdodEFj",
                  "Y2Vzc1BvaW50R3JvdXBzUmVzcG9uc2USlQEKHENyZWF0ZUFjY2Vzc1JpZ2h0",
                  "RGVzdGluYXRpb24SQC5zYWx0by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuQ3Jl",
                  "YXRlQWNjZXNzUmlnaHREZXN0aW5hdGlvblJlcXVlc3QaMy5zYWx0by5uZWJ1",
                  "bGEuYWNjZXNzcmlnaHQudjEuQWNjZXNzUmlnaHREZXN0aW5hdGlvbhKPAQoZ",
                  "R2V0QWNjZXNzUmlnaHREZXN0aW5hdGlvbhI9LnNhbHRvLm5lYnVsYS5hY2Nl",
                  "c3NyaWdodC52MS5HZXRBY2Nlc3NSaWdodERlc3RpbmF0aW9uUmVxdWVzdBoz",
                  "LnNhbHRvLm5lYnVsYS5hY2Nlc3NyaWdodC52MS5BY2Nlc3NSaWdodERlc3Rp",
                  "bmF0aW9uEqABChtMaXN0QWNjZXNzUmlnaHREZXN0aW5hdGlvbnMSPy5zYWx0",
                  "by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuTGlzdEFjY2Vzc1JpZ2h0RGVzdGlu",
                  "YXRpb25zUmVxdWVzdBpALnNhbHRvLm5lYnVsYS5hY2Nlc3NyaWdodC52MS5M",
                  "aXN0QWNjZXNzUmlnaHREZXN0aW5hdGlvbnNSZXNwb25zZRKVAQocVXBkYXRl",
                  "QWNjZXNzUmlnaHREZXN0aW5hdGlvbhJALnNhbHRvLm5lYnVsYS5hY2Nlc3Ny",
                  "aWdodC52MS5VcGRhdGVBY2Nlc3NSaWdodERlc3RpbmF0aW9uUmVxdWVzdBoz",
                  "LnNhbHRvLm5lYnVsYS5hY2Nlc3NyaWdodC52MS5BY2Nlc3NSaWdodERlc3Rp",
                  "bmF0aW9uEngKHERlbGV0ZUFjY2Vzc1JpZ2h0RGVzdGluYXRpb24SQC5zYWx0",
                  "by5uZWJ1bGEuYWNjZXNzcmlnaHQudjEuRGVsZXRlQWNjZXNzUmlnaHREZXN0",
                  "aW5hdGlvblJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHlC+QEKI2Nv",
                  "bS5zYWx0b2FwaXMubmVidWxhLmFjY2Vzc3JpZ2h0LnYxQhBBY2Nlc3NSaWdo",
                  "dFByb3RvUAFaTGdpdGh1Yi5jb20vc2FsdG9hcGlzLWludGVybmFsL3NhbHRv",
                  "YXBpcy1nby9uZWJ1bGEvYWNjZXNzcmlnaHQvdjE7YWNjZXNzcmlnaHSqAh9T",
                  "YWx0b2FwaXMuTmVidWxhLkFjY2Vzc1JpZ2h0LlYxygIfU2FsdG9hcGlzXE5l",
                  "YnVsYVxBY2Nlc3NSaWdodFxWMeICK0dQQk1ldGFkYXRhXFNhbHRvYXBpc1xO",
                  "ZWJ1bGFcQWNjZXNzUmlnaHRcVjFiBnByb3RvMw=="));
            descriptor = FileDescriptor.FromGeneratedCode(descriptorData,
                [Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, Google.Protobuf.WellKnownTypes.FieldMaskReflection.Descriptor, Type.ScheduleReflection.Descriptor,],
                new GeneratedClrTypeInfo(null, null, [
            new(typeof(AccessRight), AccessRight.Parser, ["Name", "DisplayName", "Schedules"], null, null, null, null),
            new(typeof(AccessRightAccessPoint), AccessRightAccessPoint.Parser, ["Name", "AccessPoint", "DisplayName"], null, null, null, null),
            new(typeof(AccessRightAccessPointGroup), AccessRightAccessPointGroup.Parser, ["Name", "AccessPointGroup", "DisplayName"], null, null, null, null),
            new(typeof(AccessRightDestination), AccessRightDestination.Parser, ["Name", "Destination", "DisplayName"], null, null, null, null),
            new(typeof(CreateAccessRightRequest), CreateAccessRightRequest.Parser, ["Parent", "AccessRightId", "AccessRight"], ["AccessRightId"], null, null, null),
            new(typeof(GetAccessRightRequest), GetAccessRightRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ListAccessRightsRequest), ListAccessRightsRequest.Parser, ["Parent", "PageSize", "PageToken", "Filter", "OrderBy"], null, null, null, null),
            new(typeof(ListAccessRightsResponse), ListAccessRightsResponse.Parser, ["AccessRights", "NextPageToken"], null, null, null, null),
            new(typeof(UpdateAccessRightRequest), UpdateAccessRightRequest.Parser, ["AccessRight", "UpdateMask"], null, null, null, null),
            new(typeof(DeleteAccessRightRequest), DeleteAccessRightRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(CreateAccessRightAccessPointRequest), CreateAccessRightAccessPointRequest.Parser, ["Parent", "AccessRightAccessPoint"], null, null, null, null),
            new(typeof(BatchCreateAccessRightAccessPointsRequest), BatchCreateAccessRightAccessPointsRequest.Parser, ["Parent", "Requests"], null, null, null, null),
            new(typeof(BatchCreateAccessRightAccessPointsResponse), BatchCreateAccessRightAccessPointsResponse.Parser, ["AccessRightAccessPoints"], null, null, null, null),
            new(typeof(GetAccessRightAccessPointRequest), GetAccessRightAccessPointRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ListAccessRightAccessPointsRequest), ListAccessRightAccessPointsRequest.Parser, ["Parent", "PageSize", "PageToken", "Filter", "OrderBy"], null, null, null, null),
            new(typeof(ListAccessRightAccessPointsResponse), ListAccessRightAccessPointsResponse.Parser, ["AccessRightAccessPoints", "NextPageToken"], null, null, null, null),
            new(typeof(UpdateAccessRightAccessPointRequest), UpdateAccessRightAccessPointRequest.Parser, ["AccessRightAccessPoint", "UpdateMask"], null, null, null, null),
            new(typeof(DeleteAccessRightAccessPointRequest), DeleteAccessRightAccessPointRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(CreateAccessRightAccessPointGroupRequest), CreateAccessRightAccessPointGroupRequest.Parser, ["Parent", "AccessRightAccessPointGroup"], null, null, null, null),
            new(typeof(BatchCreateAccessRightAccessPointGroupsRequest), BatchCreateAccessRightAccessPointGroupsRequest.Parser, ["Parent", "Requests"], null, null, null, null),
            new(typeof(BatchCreateAccessRightAccessPointGroupsResponse), BatchCreateAccessRightAccessPointGroupsResponse.Parser, ["AccessRightAccessPointGroups"], null, null, null, null),
            new(typeof(GetAccessRightAccessPointGroupRequest), GetAccessRightAccessPointGroupRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ListAccessRightAccessPointGroupsRequest), ListAccessRightAccessPointGroupsRequest.Parser, ["Parent", "PageSize", "PageToken", "Filter", "OrderBy"], null, null, null, null),
            new(typeof(ListAccessRightAccessPointGroupsResponse), ListAccessRightAccessPointGroupsResponse.Parser, ["AccessRightAccessPointGroups", "NextPageToken"], null, null, null, null),
            new(typeof(UpdateAccessRightAccessPointGroupRequest), UpdateAccessRightAccessPointGroupRequest.Parser, ["AccessRightAccessPointGroup", "UpdateMask"], null, null, null, null),
            new(typeof(DeleteAccessRightAccessPointGroupRequest), DeleteAccessRightAccessPointGroupRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(BatchDeleteAccessRightAccessPointGroupsRequest), BatchDeleteAccessRightAccessPointGroupsRequest.Parser, ["Parent", "Requests"], null, null, null, null),
            new(typeof(BatchDeleteAccessRightAccessPointGroupsResponse), BatchDeleteAccessRightAccessPointGroupsResponse.Parser, null, null, null, null, null),
            new(typeof(BatchDeleteAccessRightAccessPointsRequest), BatchDeleteAccessRightAccessPointsRequest.Parser, ["Parent", "Requests"], null, null, null, null),
            new(typeof(BatchDeleteAccessRightAccessPointsResponse), BatchDeleteAccessRightAccessPointsResponse.Parser, null, null, null, null, null),
            new(typeof(CreateAccessRightDestinationRequest), CreateAccessRightDestinationRequest.Parser, ["Parent", "AccessRightDestination"], null, null, null, null),
            new(typeof(GetAccessRightDestinationRequest), GetAccessRightDestinationRequest.Parser, ["Name"], null, null, null, null),
            new(typeof(ListAccessRightDestinationsRequest), ListAccessRightDestinationsRequest.Parser, ["Parent", "PageSize", "PageToken", "Filter", "OrderBy"], null, null, null, null),
            new(typeof(ListAccessRightDestinationsResponse), ListAccessRightDestinationsResponse.Parser, ["AccessRightDestinations", "NextPageToken"], null, null, null, null),
            new(typeof(UpdateAccessRightDestinationRequest), UpdateAccessRightDestinationRequest.Parser, ["AccessRightDestination", "UpdateMask"], null, null, null, null),
            new(typeof(DeleteAccessRightDestinationRequest), DeleteAccessRightDestinationRequest.Parser, ["Name"], null, null, null, null)
                ]));
        }
    }

}