name: "SALTO APIs build"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          include-prerelease: true

      - name: prepare
        run: make prepare
      - name: build
        run: make build
      - name: test
        run: make test
      - name: release
        if: github.ref == 'refs/heads/master'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: make release
